"""Portability reason codes — reuse XCAT equivalents where applicable."""

from __future__ import annotations

from enum import Enum

from spe_runtime.xcat.reasons import ReasonCode


class PortabilityReason(str, Enum):
    # Reuse XCAT equivalents
    PROVENANCE_LOST = ReasonCode.PROVENANCE_LOST.value
    UNCERTAINTY_ERASED = ReasonCode.UNCERTAINTY_ERASED.value
    CONSTRAINT_WEAKENED = ReasonCode.CONSTRAINT_WEAKENED.value
    PREFERENCE_MUTATED = ReasonCode.PREFERENCE_MUTATED.value
    AUTHORITY_SELF_ESCALATION = ReasonCode.AUTHORITY_SELF_ESCALATION.value
    SEMANTIC_REWRITE = ReasonCode.SEMANTIC_REWRITE.value
    TAINT_LOST = ReasonCode.TAINT_LOST.value
    SENSITIVITY_LOST = ReasonCode.SENSITIVITY_LOST.value
    # Portability-specific
    CAPABILITY_MISSING = "P_CAPABILITY_MISSING"
    CAPABILITY_BLOCKED = "P_CAPABILITY_BLOCKED"
    CAPABILITY_DEFER = "P_CAPABILITY_DEFER"
    ROUND_TRIP_FAIL = "P_ROUND_TRIP_FAIL"
    CANONICAL_DRIFT = "P_CANONICAL_DRIFT"
    TUPLE_LEAK = "P_TUPLE_LEAK"
    PRIVACY_ESCALATION = "P_PRIVACY_ESCALATION"
    TRUST_ESCALATION = "P_TRUST_ESCALATION"
    AUTHORITY_ESCALATION = "P_AUTHORITY_ESCALATION"
    NETWORK_FORBIDDEN = "P_NETWORK_FORBIDDEN"
    FAKE_PLATFORM_STATUS = "P_FAKE_PLATFORM_STATUS"
    ABI_MISMATCH = "P_ABI_MISMATCH"
    SCHEMA_INVALID = "P_SCHEMA_INVALID"
    OFFLINE_VIOLATION = "P_OFFLINE_VIOLATION"
    UNKNOWN_NULLIFIED = "P_UNKNOWN_NULLIFIED"
    HARD_TO_PREFERENCE = "P_HARD_TO_PREFERENCE"
    DENIED_TO_GRANTED = "P_DENIED_TO_GRANTED"
    PROVENANCE_REMOVED = "P_PROVENANCE_REMOVED"
    SEMANTIC_NONEQUIVALENT = "P_SEMANTIC_NONEQUIVALENT"
