/**
 * MM-6: Model Pack Security & Registry
 *
 * Canonical registry of qualified browser-executable ONNX model packs.
 * Enforces SHA-256 digest integrity, licensing, memory budgets, and
 * explicit-consent provisioning laws.
 *
 * INVARIANTS:
 * - NO automatic background downloads.
 * - Digest verification is mandatory before execution.
 * - Unknown executable assets are strictly rejected.
 * - RAW_USER_DATA_EGRESS = 0 is guaranteed.
 */

import { computeSha256 } from "../hashUtils";
import type {
  ModelManifest,
  ModelPack,
  ProvisioningMode,
  OfflineModelPackage,
  ModelCustodyState,
  ProvenanceVerificationTier,
  MultimodalTask,
  RuntimeBackend,
  FileSha256,
  PayloadSha256,
  ManifestDigest,
  ArchiveSha256,
  RecognizerCapability,
} from "./types";

/**
 * Computes individual file SHA-256 digest.
 */
export function computeFileSha256(bytes: Uint8Array): FileSha256 {
  return computeSha256(bytes);
}

/**
 * Computes canonical payload SHA-256 digest from actual concatenated file bytes.
 * Files are concatenated deterministically in lexicographical order of their filenames.
 */
export function computePayloadSha256(files: Record<string, Uint8Array>): PayloadSha256 {
  const sortedNames = Object.keys(files).sort();
  let totalLength = 0;
  for (const name of sortedNames) {
    totalLength += files[name].length;
  }
  const combined = new Uint8Array(totalLength);
  let offset = 0;
  for (const name of sortedNames) {
    combined.set(files[name], offset);
    offset += files[name].length;
  }
  return computeSha256(combined);
}

/**
 * Computes canonical manifest digest over serialized deterministic metadata.
 * Strips volatile/derived digest fields to avoid circularity.
 */
export function computeManifestDigest(manifest: ModelManifest | CanonicalProductionModel): ManifestDigest {
  const normalized = {
    modelId: manifest.modelId,
    version: manifest.version,
    source: (manifest as ModelManifest).source || (manifest as CanonicalProductionModel).upstreamRepository,
    license: manifest.license,
    expectedSizeBytes: (manifest as ModelManifest).expectedSizeBytes ?? (manifest as CanonicalProductionModel).totalSizeBytes,
    files: [...manifest.files]
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((f) => ({
        name: f.name,
        sizeBytes: (f as any).sizeBytes ?? (f as any).expectedSizeBytes,
        sha256: (f as any).sha256 ?? (f as any).expectedSha256,
        required: f.required,
      })),
    supportedLanguages: [...manifest.supportedLanguages].sort(),
    supportedRuntimes: [...manifest.supportedRuntimes].sort(),
  };
  return computeSha256(JSON.stringify(normalized));
}

/**
 * Computes SHA-256 over entire .spemodel archive buffer.
 */
export function computeArchiveSha256(archiveBytes: Uint8Array): ArchiveSha256 {
  return computeSha256(archiveBytes);
}

/**
 * Anti-fraud check: Ensures a claimed payload digest was not generated by hashing
 * an array of hex hash strings instead of physical binary bytes.
 */
export function verifyPayloadDigestSemantic(
  claimedPayloadSha: string,
  filesPayload: Record<string, Uint8Array>,
): void {
  const sortedNames = Object.keys(filesPayload).sort();
  const fileHashes = sortedNames.map((n) => computeSha256(filesPayload[n]));
  const stringDerived = computeSha256(fileHashes.join(":"));
  if (claimedPayloadSha.toLowerCase() === stringDerived.toLowerCase()) {
    throw new Error(
      "DIGEST_SEMANTIC_VIOLATION: Hash of file-hash strings cannot be mislabeled as payload hash",
    );
  }
}

/**
 * Disambiguates manifest metadata digest from physical artifact / payload SHA.
 */
export function verifyDigestSemanticDisambiguation(
  manifest: ModelManifest,
  claimedArtifactSha: string,
): void {
  const mDigest = manifest.manifestDigest || manifest.sha256;
  if (claimedArtifactSha.toLowerCase() === mDigest.toLowerCase()) {
    throw new Error(
      "DIGEST_SEMANTIC_VIOLATION: Manifest metadata digest cannot be mislabeled as model artifact SHA",
    );
  }
}

/**
 * Asserts that verifiedDigest is computed from real file bytes, not string labels or manifest copies.
 */
export function assertVerifiedDigestComputedFromBytes(
  verifiedDigest: string,
  filesPayload: Record<string, Uint8Array>,
): void {
  const actualPayloadSha = computePayloadSha256(filesPayload);
  if (verifiedDigest.toLowerCase() !== actualPayloadSha.toLowerCase()) {
    throw new Error(
      `DIGEST_INTEGRITY_VIOLATION: verifiedDigest '${verifiedDigest}' does not match computed payload hash '${actualPayloadSha}' over provided bytes`,
    );
  }
}

export const RECOGNIZER_CAPABILITIES: Record<string, RecognizerCapability> = {
  "paddleocr-v3-english": {
    recognizerId: "paddleocr-v3-english",
    scriptFamily: "Latin",
    supportedLanguages: ["en"],
    upstreamArtifact: "languages/english/rec.onnx",
    revision: "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65",
    dictionaryArtifact: "languages/english/dict.txt",
    detectorArtifact: "detection/v3/det.onnx",
    detectorVersion: "v3",
    recognizerVersion: "v3",
  },
  "paddleocr-v3-devanagari": {
    recognizerId: "paddleocr-v3-devanagari",
    scriptFamily: "Devanagari",
    supportedLanguages: ["hi", "mr", "ne", "sa"],
    upstreamArtifact: "languages/hindi/rec.onnx",
    revision: "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65",
    dictionaryArtifact: "languages/hindi/dict.txt",
    detectorArtifact: "detection/v3/det.onnx",
    detectorVersion: "v3",
    recognizerVersion: "v3",
  },
  "paddleocr-v3-telugu": {
    recognizerId: "paddleocr-v3-telugu",
    scriptFamily: "Telugu",
    supportedLanguages: ["te"],
    upstreamArtifact: "languages/telugu/rec.onnx",
    revision: "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65",
    dictionaryArtifact: "languages/telugu/dict.txt",
    detectorArtifact: "detection/v3/det.onnx",
    detectorVersion: "v3",
    recognizerVersion: "v3",
  },
  "paddleocr-v3-tamil": {
    recognizerId: "paddleocr-v3-tamil",
    scriptFamily: "Tamil",
    supportedLanguages: ["ta"],
    upstreamArtifact: "languages/tamil/rec.onnx",
    revision: "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65",
    dictionaryArtifact: "languages/tamil/dict.txt",
    detectorArtifact: "detection/v3/det.onnx",
    detectorVersion: "v3",
    recognizerVersion: "v3",
  },
};

export function deriveLanguagesFromRecognizer(recognizerId: string): string[] {
  const cap = RECOGNIZER_CAPABILITIES[recognizerId];
  if (!cap) {
    throw new Error(
      `UNKNOWN_RECOGNIZER_CAPABILITY: No registered capability for recognizer '${recognizerId}'`,
    );
  }
  return [...cap.supportedLanguages];
}

export interface UpstreamModelProvenanceFile {
  name: string;
  upstreamUrl: string;
  expectedSizeBytes: number;
  expectedSha256: string;
  isRealBinaryVerified: boolean;
}

export interface UpstreamModelProvenance {
  modelId: string;
  baseModel?: string;
  baseModelLicense?: "MIT" | "Apache-2.0" | "UNVERIFIED" | string;
  conversionRepoLicense?: "Apache-2.0" | "UNVERIFIED" | string;
  artifactLicenseStatus?: "VERIFIED_MIT" | "VERIFIED_APACHE_2_0" | "UNVERIFIED" | "HOLD";
  upstreamRepository: string;
  revision: string;
  recognizerCapabilityId?: string;
  license: string;
  files: UpstreamModelProvenanceFile[];
  totalSizeBytes: number;
  custodyState?: ModelCustodyState;
  custodyStatus: "CUSTODY_PENDING_DOWNLOAD" | "CUSTODY_VERIFIED" | "CUSTODY_PENDING";
  verificationTier?: ProvenanceVerificationTier;
  isLiveVerified?: boolean;
}

export interface CanonicalProductionModel {
  modelId: string;
  version: string;
  displayName: string;
  task: MultimodalTask;
  supportedTasks: MultimodalTask[];
  baseModel: string;
  baseModelLicense: "MIT" | "Apache-2.0" | string;
  conversionRepoLicense: "Apache-2.0" | "UNVERIFIED" | string;
  artifactLicenseStatus: "VERIFIED_MIT" | "VERIFIED_APACHE_2_0" | "HOLD";
  license: string;
  upstreamRepository: string;
  revision: string;
  recognizerCapabilityId?: string;
  files: Array<{
    name: string;
    upstreamUrl: string;
    sizeBytes: number;
    sha256: string;
    required: boolean;
    isRealBinaryVerified: boolean;
  }>;
  totalSizeBytes: number;
  sha256: string; // Manifest metadata digest (alias of manifestDigest)
  manifestDigest?: ManifestDigest;
  expectedPayloadSha256?: PayloadSha256;
  supportedRuntimes: RuntimeBackend[];
  supportedLanguages: string[];
  minimumMemoryMb: number;
  quantization: "INT8" | "FP16" | "FP32";
  provenance: string;
  qualificationState:
    | "DECLARED"
    | "PROVENANCE_VERIFIED"
    | "BYTES_VERIFIED"
    | "INFERENCE_VERIFIED"
    | "BENCHMARKED"
    | "QUALIFIED"
    | "CANDIDATE"
    | "MANIFEST_ONLY"
    | "ARTIFACT_UNVERIFIED"
    | "DEGRADED"
    | "FALLBACK"
    | "UNAVAILABLE"
    | "UNTESTED";
  custodyState: ModelCustodyState;
  custodyStatus: "CUSTODY_PENDING_DOWNLOAD" | "CUSTODY_VERIFIED";
  verificationTier: ProvenanceVerificationTier;
  isLiveVerified: boolean;
  opsetVersion?: number;
}

export const MODEL_PACK_SIZE_METRICS = {
  ASR_MODEL_ONLY_BYTES: 40_844_231, // encoder (10,124,990) + decoder (30,719,241)
  ASR_COMPLETE_PACK_BYTES: 43_324_697, // + tokenizer.json (2,480,466)
  OCR_EN_MODEL_ONLY_BYTES: 10_260_761, // det (2,429,873) + rec_en (7,830,888)
  OCR_EN_COMPLETE_PACK_BYTES: 10_262_177, // + dict_en (1,416)
  OCR_DEVANAGARI_COMPLETE_PACK_BYTES: 11_410_605, // det (2,429,873) + rec_hi (8,980,224) + dict_hi (508)
  OCR_TELUGU_COMPLETE_PACK_BYTES: 11_406_366, // det (2,429,873) + rec_te (8,976,064) + dict_te (429)
  OCR_TAMIL_COMPLETE_PACK_BYTES: 11_400_309, // det (2,429,873) + rec_ta (8,970,084) + dict_ta (352)
  OCR_PADDLE_MODEL_ONLY_BYTES: 10_260_761,
  OCR_PADDLE_COMPLETE_PACK_BYTES: 10_262_177,
  OCR_MOBILE_MODEL_ONLY_BYTES: 10_260_761,
  OCR_MOBILE_COMPLETE_PACK_BYTES: 10_262_177,
  OCR_TROCR_MODEL_ONLY_BYTES: 28_500_000,
  OCR_TROCR_COMPLETE_PACK_BYTES: 28_600_000,
  RUNTIME_SHARED_BYTES: 11_246_030, // ort-wasm-simd-threaded.wasm
} as const;

export const CACHED_VERIFIED_UPSTREAM_METADATA: Record<
  string,
  {
    repoUrl: string;
    verifiedRevisions: Record<
      string,
      {
        baseModel: string;
        baseModelLicense: string;
        conversionRepoLicense: string;
        artifactLicenseStatus: string;
        files: Record<string, { sizeBytes: number; sha256: string }>;
      }
    >;
  }
> = {
  "https://huggingface.co/onnx-community/whisper-tiny": {
    repoUrl: "https://huggingface.co/onnx-community/whisper-tiny",
    verifiedRevisions: {
      "6d4fb5abc94227ee92e43fc5091278851eadf8a0": {
        baseModel: "openai/whisper-tiny",
        baseModelLicense: "MIT",
        conversionRepoLicense: "UNVERIFIED",
        artifactLicenseStatus: "HOLD",
        files: {
          "encoder_model_quantized.onnx": {
            sizeBytes: 10_124_990,
            sha256: "2af4a414ca47aa30f61246017e5fe82b0a8d229281d1255ba666a2a7f6b84d19",
          },
          "onnx/encoder_model_quantized.onnx": {
            sizeBytes: 10_124_990,
            sha256: "2af4a414ca47aa30f61246017e5fe82b0a8d229281d1255ba666a2a7f6b84d19",
          },
          "decoder_model_merged_quantized.onnx": {
            sizeBytes: 30_719_241,
            sha256: "25e807a962b6349356d0ea5d0dfe530b7e5bf0e2a484aeca0359d03143faddd3",
          },
          "onnx/decoder_model_merged_quantized.onnx": {
            sizeBytes: 30_719_241,
            sha256: "25e807a962b6349356d0ea5d0dfe530b7e5bf0e2a484aeca0359d03143faddd3",
          },
          "tokenizer.json": {
            sizeBytes: 2_480_466,
            sha256: "27fc476bfe7f17299480be2273fc0608e4d5a99aba2ab5dec5374b4482d1a566",
          },
        },
      },
    },
  },
  "https://huggingface.co/monkt/paddleocr-onnx": {
    repoUrl: "https://huggingface.co/monkt/paddleocr-onnx",
    verifiedRevisions: {
      "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65": {
        baseModel: "PaddlePaddle/PaddleOCR PP-OCRv3/v4",
        baseModelLicense: "Apache-2.0",
        conversionRepoLicense: "Apache-2.0",
        artifactLicenseStatus: "VERIFIED_APACHE_2_0",
        files: {
          "det.onnx": {
            sizeBytes: 2_429_873,
            sha256: "ee40e80071ba3a320d4efda75f3e22047a7d049e9bf7bcaaf9daea23fc21b935",
          },
          "detection/v3/det.onnx": {
            sizeBytes: 2_429_873,
            sha256: "ee40e80071ba3a320d4efda75f3e22047a7d049e9bf7bcaaf9daea23fc21b935",
          },
          "rec.onnx": {
            sizeBytes: 7_830_888,
            sha256: "4e16deb22c4da6468bdca539b2cd3c8687825538b67109177c47d359ab994cd7",
          },
          "languages/english/rec.onnx": {
            sizeBytes: 7_830_888,
            sha256: "4e16deb22c4da6468bdca539b2cd3c8687825538b67109177c47d359ab994cd7",
          },
          "dict.txt": {
            sizeBytes: 1_416,
            sha256: "e025a66d31f327ba0c232e03f407ae8d105e1e709e7ccb3f408aa778c24e70d6",
          },
          "languages/english/dict.txt": {
            sizeBytes: 1_416,
            sha256: "e025a66d31f327ba0c232e03f407ae8d105e1e709e7ccb3f408aa778c24e70d6",
          },
          "languages/hindi/rec.onnx": {
            sizeBytes: 8_980_224,
            sha256: "43df175fa3c877fbf7bcc4e5bd1e203e24ec450cd3ea96c9e802c86e39a4d4cf",
          },
          "languages/telugu/rec.onnx": {
            sizeBytes: 8_976_064,
            sha256: "669946d9ad4de93e8d1b13f7e72c59cc2cc2de91bb24e22aad7503a6cc5757ee",
          },
          "languages/tamil/rec.onnx": {
            sizeBytes: 8_970_084,
            sha256: "fba9a00af746c8f3ef4f091cf966880222cd7245a60f6a953670593630c0ca4f",
          },
          "detection/v5/det.onnx": {
            sizeBytes: 88_030_804,
            sha256: "61824840edf6e74581898930b8091b1b2318f4b2705a2e8a40ad3de7ac480133",
          },
          "languages/hindi/dict.txt": {
            sizeBytes: 508,
            sha256: "b5f1be6d8bbff1a19fb96c5d4ca96a423380234bb7d2ce0e07b5838adb4d18ea",
          },
          "languages/telugu/dict.txt": {
            sizeBytes: 429,
            sha256: "ee9946a60d7701977474e89883694a4ca20eaa3868a23334bf7940dcd008f0f9",
          },
          "languages/tamil/dict.txt": {
            sizeBytes: 352,
            sha256: "e93e694814afd9ff1e918b6f4bb4267fb4c65a9344ee5d7464f9135b90c0a270",
          },
        },
      },
    },
  },
};

export const VERIFIED_UPSTREAM_REPOSITORIES = CACHED_VERIFIED_UPSTREAM_METADATA;

export const CANONICAL_PRODUCTION_MODELS: Record<string, CanonicalProductionModel> = {
  "spe-whisper-tiny-int8": {
    modelId: "spe-whisper-tiny-int8",
    version: "1.0.0",
    displayName: "Whisper Tiny INT8 (Local Multilingual ASR)",
    task: "asr-speech-transcription",
    supportedTasks: ["asr-speech-transcription"],
    baseModel: "openai/whisper-tiny",
    baseModelLicense: "MIT",
    conversionRepoLicense: "UNVERIFIED",
    artifactLicenseStatus: "HOLD",
    license: "MIT",
    upstreamRepository: "https://huggingface.co/onnx-community/whisper-tiny",
    revision: "6d4fb5abc94227ee92e43fc5091278851eadf8a0",
    files: [
      {
        name: "encoder_model_quantized.onnx",
        upstreamUrl: "https://huggingface.co/onnx-community/whisper-tiny/resolve/6d4fb5abc94227ee92e43fc5091278851eadf8a0/onnx/encoder_model_quantized.onnx",
        sizeBytes: 10_124_990,
        sha256: "2af4a414ca47aa30f61246017e5fe82b0a8d229281d1255ba666a2a7f6b84d19",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "decoder_model_merged_quantized.onnx",
        upstreamUrl: "https://huggingface.co/onnx-community/whisper-tiny/resolve/6d4fb5abc94227ee92e43fc5091278851eadf8a0/onnx/decoder_model_merged_quantized.onnx",
        sizeBytes: 30_719_241,
        sha256: "25e807a962b6349356d0ea5d0dfe530b7e5bf0e2a484aeca0359d03143faddd3",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "tokenizer.json",
        upstreamUrl: "https://huggingface.co/onnx-community/whisper-tiny/resolve/6d4fb5abc94227ee92e43fc5091278851eadf8a0/tokenizer.json",
        sizeBytes: 2_480_466,
        sha256: "27fc476bfe7f17299480be2273fc0608e4d5a99aba2ab5dec5374b4482d1a566",
        required: true,
        isRealBinaryVerified: false,
      },
    ],
    totalSizeBytes: 43_324_697,
    sha256: "4a9a6324601da120b3ab5369856f29e60389334501ae840a569962c390bb8ec7",
    manifestDigest: "4a9a6324601da120b3ab5369856f29e60389334501ae840a569962c390bb8ec7",
    supportedRuntimes: ["WEBGPU", "WASM"],
    supportedLanguages: [
      "en", "es", "zh", "hi", "ar", "bn", "pt", "ru", "ja", "de",
      "fr", "te", "ta", "id", "ur", "ko", "it", "tr", "vi", "mr"
    ],
    minimumMemoryMb: 256,
    quantization: "INT8",
    provenance: "Vetted HuggingFace onnx-community/whisper-tiny commit 6d4fb5a...; base model MIT; conversion license unverified (HOLD); real binary verification PENDING",
    qualificationState: "DECLARED",
    custodyState: "SOURCE_VERIFIED",
    custodyStatus: "CUSTODY_PENDING_DOWNLOAD",
    verificationTier: "CACHED_SOURCE_VERIFIED",
    isLiveVerified: false,
    opsetVersion: 17,
  },
  "spe-ocr-en": {
    modelId: "spe-ocr-en",
    version: "3.0.0",
    displayName: "PaddleOCR v3 English/Latin OCR (Local)",
    task: "ocr-text-recognition",
    supportedTasks: ["ocr-text-recognition"],
    baseModel: "PaddlePaddle/PaddleOCR PP-OCRv3/v4",
    baseModelLicense: "Apache-2.0",
    conversionRepoLicense: "Apache-2.0",
    artifactLicenseStatus: "VERIFIED_APACHE_2_0",
    license: "Apache-2.0",
    upstreamRepository: "https://huggingface.co/monkt/paddleocr-onnx",
    revision: "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65",
    recognizerCapabilityId: "paddleocr-v3-english",
    files: [
      {
        name: "det.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/detection/v3/det.onnx",
        sizeBytes: 2_429_873,
        sha256: "ee40e80071ba3a320d4efda75f3e22047a7d049e9bf7bcaaf9daea23fc21b935",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "rec.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/english/rec.onnx",
        sizeBytes: 7_830_888,
        sha256: "4e16deb22c4da6468bdca539b2cd3c8687825538b67109177c47d359ab994cd7",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "dict.txt",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/english/dict.txt",
        sizeBytes: 1_416,
        sha256: "e025a66d31f327ba0c232e03f407ae8d105e1e709e7ccb3f408aa778c24e70d6",
        required: true,
        isRealBinaryVerified: false,
      },
    ],
    totalSizeBytes: 10_262_177,
    sha256: "3d25f6c16028f4fb59c60e8ee29d937f58ad464bc7435985ee54e2be198c09a8",
    manifestDigest: "3d25f6c16028f4fb59c60e8ee29d937f58ad464bc7435985ee54e2be198c09a8",
    supportedRuntimes: ["WEBGPU", "WASM"],
    supportedLanguages: deriveLanguagesFromRecognizer("paddleocr-v3-english"),
    minimumMemoryMb: 192,
    quantization: "INT8",
    provenance: "PaddlePaddle PP-OCRv3 English OCR weights via monkt/paddleocr-onnx commit 7b02d0a...; Apache-2.0; real binary verification PENDING",
    qualificationState: "DECLARED",
    custodyState: "SOURCE_VERIFIED",
    custodyStatus: "CUSTODY_PENDING_DOWNLOAD",
    verificationTier: "CACHED_SOURCE_VERIFIED",
    isLiveVerified: false,
    opsetVersion: 17,
  },
  "spe-ocr-devanagari": {
    modelId: "spe-ocr-devanagari",
    version: "3.0.0",
    displayName: "PaddleOCR v3 Devanagari OCR (Hindi, Marathi, Nepali)",
    task: "ocr-text-recognition",
    supportedTasks: ["ocr-text-recognition"],
    baseModel: "PaddlePaddle/PaddleOCR PP-OCRv3/v4",
    baseModelLicense: "Apache-2.0",
    conversionRepoLicense: "Apache-2.0",
    artifactLicenseStatus: "VERIFIED_APACHE_2_0",
    license: "Apache-2.0",
    upstreamRepository: "https://huggingface.co/monkt/paddleocr-onnx",
    revision: "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65",
    recognizerCapabilityId: "paddleocr-v3-devanagari",
    files: [
      {
        name: "det.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/detection/v3/det.onnx",
        sizeBytes: 2_429_873,
        sha256: "ee40e80071ba3a320d4efda75f3e22047a7d049e9bf7bcaaf9daea23fc21b935",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "rec.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/hindi/rec.onnx",
        sizeBytes: 8_980_224,
        sha256: "43df175fa3c877fbf7bcc4e5bd1e203e24ec450cd3ea96c9e802c86e39a4d4cf",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "dict.txt",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/hindi/dict.txt",
        sizeBytes: 508,
        sha256: "b5f1be6d8bbff1a19fb96c5d4ca96a423380234bb7d2ce0e07b5838adb4d18ea",
        required: true,
        isRealBinaryVerified: false,
      },
    ],
    totalSizeBytes: 11_410_605,
    sha256: "a01739d17d7ae34bc0ea8cdde8a337da2a9db23cbe19b88cf9bfbf85299309fd",
    manifestDigest: "a01739d17d7ae34bc0ea8cdde8a337da2a9db23cbe19b88cf9bfbf85299309fd",
    supportedRuntimes: ["WEBGPU", "WASM"],
    supportedLanguages: deriveLanguagesFromRecognizer("paddleocr-v3-devanagari"),
    minimumMemoryMb: 192,
    quantization: "INT8",
    provenance: "PaddlePaddle PP-OCRv3 Devanagari OCR weights via monkt/paddleocr-onnx commit 7b02d0a...; Apache-2.0; real binary verification PENDING",
    qualificationState: "DECLARED",
    custodyState: "SOURCE_VERIFIED",
    custodyStatus: "CUSTODY_PENDING_DOWNLOAD",
    verificationTier: "CACHED_SOURCE_VERIFIED",
    isLiveVerified: false,
    opsetVersion: 17,
  },
  "spe-ocr-telugu": {
    modelId: "spe-ocr-telugu",
    version: "3.0.0",
    displayName: "PaddleOCR v3 Telugu OCR (Local)",
    task: "ocr-text-recognition",
    supportedTasks: ["ocr-text-recognition"],
    baseModel: "PaddlePaddle/PaddleOCR PP-OCRv3/v4",
    baseModelLicense: "Apache-2.0",
    conversionRepoLicense: "Apache-2.0",
    artifactLicenseStatus: "VERIFIED_APACHE_2_0",
    license: "Apache-2.0",
    upstreamRepository: "https://huggingface.co/monkt/paddleocr-onnx",
    revision: "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65",
    recognizerCapabilityId: "paddleocr-v3-telugu",
    files: [
      {
        name: "det.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/detection/v3/det.onnx",
        sizeBytes: 2_429_873,
        sha256: "ee40e80071ba3a320d4efda75f3e22047a7d049e9bf7bcaaf9daea23fc21b935",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "rec.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/telugu/rec.onnx",
        sizeBytes: 8_976_064,
        sha256: "669946d9ad4de93e8d1b13f7e72c59cc2cc2de91bb24e22aad7503a6cc5757ee",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "dict.txt",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/telugu/dict.txt",
        sizeBytes: 429,
        sha256: "ee9946a60d7701977474e89883694a4ca20eaa3868a23334bf7940dcd008f0f9",
        required: true,
        isRealBinaryVerified: false,
      },
    ],
    totalSizeBytes: 11_406_366,
    sha256: "302798f69aff561271d667462d3a8fa8e31f4476ae5079c7e81c975c59bc70c8",
    manifestDigest: "302798f69aff561271d667462d3a8fa8e31f4476ae5079c7e81c975c59bc70c8",
    supportedRuntimes: ["WEBGPU", "WASM"],
    supportedLanguages: deriveLanguagesFromRecognizer("paddleocr-v3-telugu"),
    minimumMemoryMb: 192,
    quantization: "INT8",
    provenance: "PaddlePaddle PP-OCRv3 Telugu OCR weights via monkt/paddleocr-onnx commit 7b02d0a...; Apache-2.0; real binary verification PENDING",
    qualificationState: "DECLARED",
    custodyState: "SOURCE_VERIFIED",
    custodyStatus: "CUSTODY_PENDING_DOWNLOAD",
    verificationTier: "CACHED_SOURCE_VERIFIED",
    isLiveVerified: false,
    opsetVersion: 17,
  },
  "spe-ocr-tamil": {
    modelId: "spe-ocr-tamil",
    version: "3.0.0",
    displayName: "PaddleOCR v3 Tamil OCR (Local)",
    task: "ocr-text-recognition",
    supportedTasks: ["ocr-text-recognition"],
    baseModel: "PaddlePaddle/PaddleOCR PP-OCRv3/v4",
    baseModelLicense: "Apache-2.0",
    conversionRepoLicense: "Apache-2.0",
    artifactLicenseStatus: "VERIFIED_APACHE_2_0",
    license: "Apache-2.0",
    upstreamRepository: "https://huggingface.co/monkt/paddleocr-onnx",
    revision: "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65",
    recognizerCapabilityId: "paddleocr-v3-tamil",
    files: [
      {
        name: "det.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/detection/v3/det.onnx",
        sizeBytes: 2_429_873,
        sha256: "ee40e80071ba3a320d4efda75f3e22047a7d049e9bf7bcaaf9daea23fc21b935",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "rec.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/tamil/rec.onnx",
        sizeBytes: 8_970_084,
        sha256: "fba9a00af746c8f3ef4f091cf966880222cd7245a60f6a953670593630c0ca4f",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "dict.txt",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/tamil/dict.txt",
        sizeBytes: 352,
        sha256: "e93e694814afd9ff1e918b6f4bb4267fb4c65a9344ee5d7464f9135b90c0a270",
        required: true,
        isRealBinaryVerified: false,
      },
    ],
    totalSizeBytes: 11_400_309,
    sha256: "f50b7edef672e0e637e0d2b05e561cb5aa421959a0dda17208a9bc9bcb1a7bed",
    manifestDigest: "f50b7edef672e0e637e0d2b05e561cb5aa421959a0dda17208a9bc9bcb1a7bed",
    supportedRuntimes: ["WEBGPU", "WASM"],
    supportedLanguages: deriveLanguagesFromRecognizer("paddleocr-v3-tamil"),
    minimumMemoryMb: 192,
    quantization: "INT8",
    provenance: "PaddlePaddle PP-OCRv3 Tamil OCR weights via monkt/paddleocr-onnx commit 7b02d0a...; Apache-2.0; real binary verification PENDING",
    qualificationState: "DECLARED",
    custodyState: "SOURCE_VERIFIED",
    custodyStatus: "CUSTODY_PENDING_DOWNLOAD",
    verificationTier: "CACHED_SOURCE_VERIFIED",
    isLiveVerified: false,
    opsetVersion: 17,
  },
  "spe-ocr-paddle-int8": {
    modelId: "spe-ocr-paddle-int8",
    version: "4.0.0",
    displayName: "PaddleOCR v3/v4 ONNX (English/Latin Recognition)",
    task: "ocr-text-recognition",
    supportedTasks: ["ocr-text-recognition"],
    baseModel: "PaddlePaddle/PaddleOCR PP-OCRv3/v4",
    baseModelLicense: "Apache-2.0",
    conversionRepoLicense: "Apache-2.0",
    artifactLicenseStatus: "VERIFIED_APACHE_2_0",
    license: "Apache-2.0",
    upstreamRepository: "https://huggingface.co/monkt/paddleocr-onnx",
    revision: "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65",
    recognizerCapabilityId: "paddleocr-v3-english",
    files: [
      {
        name: "det.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/detection/v3/det.onnx",
        sizeBytes: 2_429_873,
        sha256: "ee40e80071ba3a320d4efda75f3e22047a7d049e9bf7bcaaf9daea23fc21b935",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "rec.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/english/rec.onnx",
        sizeBytes: 7_830_888,
        sha256: "4e16deb22c4da6468bdca539b2cd3c8687825538b67109177c47d359ab994cd7",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "dict.txt",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/english/dict.txt",
        sizeBytes: 1_416,
        sha256: "e025a66d31f327ba0c232e03f407ae8d105e1e709e7ccb3f408aa778c24e70d6",
        required: true,
        isRealBinaryVerified: false,
      },
    ],
    totalSizeBytes: 10_262_177,
    sha256: "3d25f6c16028f4fb59c60e8ee29d937f58ad464bc7435985ee54e2be198c09a8",
    manifestDigest: "3d25f6c16028f4fb59c60e8ee29d937f58ad464bc7435985ee54e2be198c09a8",
    supportedRuntimes: ["WEBGPU", "WASM"],
    supportedLanguages: deriveLanguagesFromRecognizer("paddleocr-v3-english"),
    minimumMemoryMb: 192,
    quantization: "INT8",
    provenance: "PaddlePaddle PP-OCRv3/v4 ONNX weights via monkt/paddleocr-onnx commit 7b02d0a...; Apache-2.0; real binary verification PENDING",
    qualificationState: "DECLARED",
    custodyState: "SOURCE_VERIFIED",
    custodyStatus: "CUSTODY_PENDING_DOWNLOAD",
    verificationTier: "CACHED_SOURCE_VERIFIED",
    isLiveVerified: false,
    opsetVersion: 17,
  },
  "spe-ocr-multilingual-int8": {
    modelId: "spe-ocr-multilingual-int8",
    version: "4.0.0",
    displayName: "Multilingual OCR INT8 (PaddleOCR PP-OCRv3/v4 English Alias)",
    task: "ocr-text-recognition",
    supportedTasks: ["ocr-text-recognition"],
    baseModel: "PaddlePaddle/PaddleOCR PP-OCRv3/v4",
    baseModelLicense: "Apache-2.0",
    conversionRepoLicense: "Apache-2.0",
    artifactLicenseStatus: "VERIFIED_APACHE_2_0",
    license: "Apache-2.0",
    upstreamRepository: "https://huggingface.co/monkt/paddleocr-onnx",
    revision: "7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65",
    recognizerCapabilityId: "paddleocr-v3-english",
    files: [
      {
        name: "det.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/detection/v3/det.onnx",
        sizeBytes: 2_429_873,
        sha256: "ee40e80071ba3a320d4efda75f3e22047a7d049e9bf7bcaaf9daea23fc21b935",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "rec.onnx",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/english/rec.onnx",
        sizeBytes: 7_830_888,
        sha256: "4e16deb22c4da6468bdca539b2cd3c8687825538b67109177c47d359ab994cd7",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "dict.txt",
        upstreamUrl: "https://huggingface.co/monkt/paddleocr-onnx/resolve/7b02d0a30a07ba2b92ad1ff5a8941ae2c633de65/languages/english/dict.txt",
        sizeBytes: 1_416,
        sha256: "e025a66d31f327ba0c232e03f407ae8d105e1e709e7ccb3f408aa778c24e70d6",
        required: true,
        isRealBinaryVerified: false,
      },
    ],
    totalSizeBytes: 10_262_177,
    sha256: "3d25f6c16028f4fb59c60e8ee29d937f58ad464bc7435985ee54e2be198c09a8",
    manifestDigest: "3d25f6c16028f4fb59c60e8ee29d937f58ad464bc7435985ee54e2be198c09a8",
    supportedRuntimes: ["WEBGPU", "WASM"],
    supportedLanguages: deriveLanguagesFromRecognizer("paddleocr-v3-english"),
    minimumMemoryMb: 128,
    quantization: "INT8",
    provenance: "PaddlePaddle PP-OCRv3/v4 text detection and English recognition weights via monkt/paddleocr-onnx commit 7b02d0a...; real binary verification PENDING",
    qualificationState: "DECLARED",
    custodyState: "SOURCE_VERIFIED",
    custodyStatus: "CUSTODY_PENDING_DOWNLOAD",
    verificationTier: "CACHED_SOURCE_VERIFIED",
    isLiveVerified: false,
    opsetVersion: 17,
  },
  "spe-ui-segmenter-int8": {
    modelId: "spe-ui-segmenter-int8",
    version: "1.0.0",
    displayName: "MobileNetV2 UI Component Segmenter INT8",
    task: "ui-segmentation",
    supportedTasks: ["ui-segmentation"],
    baseModel: "google/mobilenet_v2",
    baseModelLicense: "Apache-2.0",
    conversionRepoLicense: "UNVERIFIED",
    artifactLicenseStatus: "HOLD",
    license: "Apache-2.0",
    upstreamRepository: "google/mobilenet_v2",
    revision: "UNVERIFIED_CANDIDATE",
    files: [
      {
        name: "mobilenetv2_ui_int8.onnx",
        upstreamUrl: "google/mobilenet_v2/mobilenetv2_ui_int8.onnx",
        sizeBytes: 3_400_000,
        sha256: "cd80774aa0b491f992f4b46d5f05772251a4a0a0356f2cf33af033650f8bdd9d",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "ui_classes.json",
        upstreamUrl: "google/mobilenet_v2/ui_classes.json",
        sizeBytes: 50_000,
        sha256: "74d0015796233105d0e7120b7143bb2a1a8cfb14e3066743d8c86d26e98899f2",
        required: true,
        isRealBinaryVerified: false,
      },
    ],
    totalSizeBytes: 3_450_000,
    sha256: "133f13472e0d8458f076ea20371f93249847094fe0a2edc1b1fd493edf16d76f",
    supportedRuntimes: ["WEBGPU", "WASM"],
    supportedLanguages: ["all"],
    minimumMemoryMb: 64,
    quantization: "INT8",
    provenance: "Client-side structural layout classifier for screenshot regions; real binary verification PENDING",
    qualificationState: "ARTIFACT_UNVERIFIED",
    custodyState: "DECLARED",
    custodyStatus: "CUSTODY_PENDING_DOWNLOAD",
    verificationTier: "UNVERIFIED",
    isLiveVerified: false,
    opsetVersion: 17,
  },
  "spe-ocr-trocr-int8": {
    modelId: "spe-ocr-trocr-int8",
    version: "1.0.0",
    displayName: "TrOCR Small INT8 (Candidate Transformer OCR)",
    task: "ocr-text-recognition",
    supportedTasks: ["ocr-text-recognition"],
    baseModel: "microsoft/trocr-small-printed",
    baseModelLicense: "Apache-2.0",
    conversionRepoLicense: "UNVERIFIED",
    artifactLicenseStatus: "HOLD",
    license: "Apache-2.0",
    upstreamRepository: "microsoft/trocr-small-printed",
    revision: "UNVERIFIED_CANDIDATE",
    files: [
      {
        name: "trocr_encoder_int8.onnx",
        upstreamUrl: "microsoft/trocr-small-printed/trocr_encoder_int8.onnx",
        sizeBytes: 12_400_000,
        sha256: "6e90fb69bf58101b6a07f8017eead48fa7b7eb60b75b2d8115553755c7df5d7b",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "trocr_decoder_int8.onnx",
        upstreamUrl: "microsoft/trocr-small-printed/trocr_decoder_int8.onnx",
        sizeBytes: 16_100_000,
        sha256: "ea4fc62d9222b0adfe5e940f9b61b76e0361dd221027334a23833052b665c984",
        required: true,
        isRealBinaryVerified: false,
      },
      {
        name: "tokenizer.json",
        upstreamUrl: "microsoft/trocr-small-printed/tokenizer.json",
        sizeBytes: 100_000,
        sha256: "55d26bba1cee2bf6efa67ff04a73ca0bc41f3908ed3d1ccb131390f5d0e394f9",
        required: true,
        isRealBinaryVerified: false,
      },
    ],
    totalSizeBytes: 28_600_000,
    sha256: "d1cf262b80015d76cf9fa3c30c0fca6bcce5bc0b38147d4ef58178d8887d950e",
    supportedRuntimes: ["WEBGPU", "WASM"],
    supportedLanguages: ["en", "es", "fr", "de", "pt", "it", "nl", "pl", "code"],
    minimumMemoryMb: 256,
    quantization: "INT8",
    provenance: "Transformer-based TrOCR Small candidate model; real binary verification PENDING",
    qualificationState: "ARTIFACT_UNVERIFIED",
    custodyState: "DECLARED",
    custodyStatus: "CUSTODY_PENDING_DOWNLOAD",
    verificationTier: "UNVERIFIED",
    isLiveVerified: false,
    opsetVersion: 17,
  },
};

/**
 * Derives runtime ModelManifest directly from canonical production provenance record.
 * Guarantees zero divergence between provenance and runtime manifest.
 */
export function deriveModelManifestFromProvenance(
  prov: CanonicalProductionModel,
): ModelManifest {
  return {
    modelId: prov.modelId,
    version: prov.version,
    displayName: prov.displayName,
    task: prov.task,
    supportedTasks: prov.supportedTasks,
    source: prov.upstreamRepository,
    license: prov.license,
    expectedSizeBytes: prov.totalSizeBytes,
    sha256: prov.sha256,
    manifestDigest: prov.manifestDigest || prov.sha256,
    expectedPayloadSha256: prov.expectedPayloadSha256 || prov.sha256,
    recognizerCapabilityId: prov.recognizerCapabilityId,
    artifactLicenseStatus: prov.artifactLicenseStatus,
    files: prov.files.map((f) => ({
      name: f.name,
      sizeBytes: f.sizeBytes,
      sha256: f.sha256,
      required: f.required,
    })),
    supportedRuntimes: prov.supportedRuntimes,
    supportedLanguages: prov.supportedLanguages,
    minimumMemoryMb: prov.minimumMemoryMb,
    quantization: prov.quantization,
    provenance: prov.provenance,
    qualificationState: prov.qualificationState,
    opsetVersion: prov.opsetVersion,
  };
}

export const PRODUCTION_MODEL_PROVENANCE: Record<string, UpstreamModelProvenance> = Object.fromEntries(
  Object.entries(CANONICAL_PRODUCTION_MODELS).map(([k, v]) => [
    k,
    {
      modelId: v.modelId,
      baseModel: v.baseModel,
      baseModelLicense: v.baseModelLicense,
      conversionRepoLicense: v.conversionRepoLicense,
      artifactLicenseStatus: v.artifactLicenseStatus,
      upstreamRepository: v.upstreamRepository,
      revision: v.revision,
      recognizerCapabilityId: v.recognizerCapabilityId,
      license: v.license,
      files: v.files.map((f) => ({
        name: f.name,
        upstreamUrl: f.upstreamUrl,
        expectedSizeBytes: f.sizeBytes,
        expectedSha256: f.sha256,
        isRealBinaryVerified: f.isRealBinaryVerified,
      })),
      totalSizeBytes: v.totalSizeBytes,
      custodyState: v.custodyState,
      custodyStatus: v.custodyStatus,
      verificationTier: v.verificationTier,
      isLiveVerified: v.isLiveVerified,
    },
  ]),
);

export const VETTED_MODEL_MANIFESTS: Record<string, ModelManifest> = Object.fromEntries(
  Object.entries(CANONICAL_PRODUCTION_MODELS).map(([k, v]) => [
    k,
    deriveModelManifestFromProvenance(v),
  ]),
);

export const STALE_MODEL_IDENTITIES = [
  "onnx-community/whisper-tiny-onnx-int8",
  "whisper-tiny-onnx-int8",
  "onnx-community/mobile-ocr-multilingual-int8",
  "mobile-ocr-multilingual-int8",
  "onnx-community/paddleocr-v4-int8",
  "paddleocr-v4-int8",
  "onnx-community/mobilenetv2-ui-int8",
  "mobilenetv2-ui-int8",
  "onnx-community/trocr-small-int8",
  "trocr-small-int8",
];

/**
 * Asserts that no stale, fabricated, or unverified repository names survive in manifests.
 */
export function assertNoStaleModelIdentities(manifests: Record<string, ModelManifest>): void {
  for (const [id, m] of Object.entries(manifests)) {
    for (const stale of STALE_MODEL_IDENTITIES) {
      if (m.source.includes(stale) || (m.provenance && m.provenance.includes(stale))) {
        throw new Error(
          `STALE_MODEL_IDENTITY: Model '${id}' contains stale unverified identity '${stale}' (found in source: '${m.source}')`,
        );
      }
    }
  }
}

/**
 * Cross-validates runtime manifest against canonical upstream provenance.
 * Throws MANIFEST_PROVENANCE_MISMATCH on any discrepancy.
 */
export function assertManifestProvenanceConsistency(
  manifest: ModelManifest,
  prov: UpstreamModelProvenance,
): void {
  if (!manifest || !prov) {
    throw new Error("MANIFEST_PROVENANCE_MISMATCH: Missing manifest or provenance record");
  }
  if (manifest.modelId !== prov.modelId) {
    throw new Error(
      `MANIFEST_PROVENANCE_MISMATCH: modelId mismatch ('${manifest.modelId}' vs '${prov.modelId}')`,
    );
  }
  if (manifest.source !== prov.upstreamRepository) {
    throw new Error(
      `MANIFEST_PROVENANCE_MISMATCH: Source repository mismatch for ${manifest.modelId}: manifest has '${manifest.source}', provenance has '${prov.upstreamRepository}'`,
    );
  }
  if (manifest.license !== prov.license) {
    throw new Error(
      `MANIFEST_PROVENANCE_MISMATCH: License mismatch for ${manifest.modelId}: manifest has '${manifest.license}', provenance has '${prov.license}'`,
    );
  }
  if (manifest.expectedSizeBytes !== prov.totalSizeBytes) {
    throw new Error(
      `MANIFEST_PROVENANCE_MISMATCH: Expected size mismatch for ${manifest.modelId}: manifest has ${manifest.expectedSizeBytes} bytes, provenance has ${prov.totalSizeBytes} bytes`,
    );
  }

  const provFileMap = new Map(prov.files.map((f) => [f.name, f]));
  for (const mf of manifest.files) {
    const pf = provFileMap.get(mf.name);
    if (!pf) {
      throw new Error(
        `MANIFEST_PROVENANCE_MISMATCH: File '${mf.name}' in manifest not found in provenance for ${manifest.modelId}`,
      );
    }
    if (mf.sizeBytes !== pf.expectedSizeBytes) {
      throw new Error(
        `MANIFEST_PROVENANCE_MISMATCH: File size mismatch for '${mf.name}' in ${manifest.modelId}: manifest has ${mf.sizeBytes}, provenance has ${pf.expectedSizeBytes}`,
      );
    }
    if (mf.sha256.toLowerCase() !== pf.expectedSha256.toLowerCase()) {
      throw new Error(
        `MANIFEST_PROVENANCE_MISMATCH: File SHA mismatch for '${mf.name}' in ${manifest.modelId}: manifest has ${mf.sha256}, provenance has ${pf.expectedSha256}`,
      );
    }
  }
  if (prov.recognizerCapabilityId && manifest.recognizerCapabilityId !== prov.recognizerCapabilityId) {
    throw new Error(
      `MANIFEST_PROVENANCE_MISMATCH: recognizerCapabilityId mismatch for ${manifest.modelId}: manifest has '${manifest.recognizerCapabilityId}', provenance has '${prov.recognizerCapabilityId}'`,
    );
  }
  if (prov.artifactLicenseStatus && manifest.artifactLicenseStatus !== prov.artifactLicenseStatus) {
    throw new Error(
      `MANIFEST_PROVENANCE_MISMATCH: artifactLicenseStatus mismatch for ${manifest.modelId}: manifest has '${manifest.artifactLicenseStatus}', provenance has '${prov.artifactLicenseStatus}'`,
    );
  }
  if (manifest.files.length !== prov.files.length) {
    throw new Error(
      `MANIFEST_PROVENANCE_MISMATCH: File count mismatch in ${manifest.modelId}: manifest has ${manifest.files.length}, provenance has ${prov.files.length}`,
    );
  }
}

/**
 * Asserts semantic validity of model manifests against physical capability and task laws.
 * Rejects task/artifact mismatches, script/recognizer overclaims, and invalid version pairings.
 */
export function assertSemanticModelValidity(
  model: ModelManifest | CanonicalProductionModel,
  prov?: UpstreamModelProvenance | CanonicalProductionModel,
): void {
  if (!model) {
    throw new Error("SEMANTIC_MODEL_INVALID: Model definition is missing");
  }

  const fileNames = new Set(model.files.map((f) => f.name));

  // 1. Task matches artifacts
  if ((model.task as string) === "speech-to-text" || model.task === "asr-speech-transcription") {
    const hasEncoder = [...fileNames].some((n) => n.includes("encoder") && n.endsWith(".onnx"));
    const hasDecoder = [...fileNames].some((n) => n.includes("decoder") && n.endsWith(".onnx"));
    if (!hasEncoder || !hasDecoder) {
      throw new Error(
        `SEMANTIC_MODEL_INVALID: Task '${model.task}' for '${model.modelId}' requires encoder and decoder ONNX models`,
      );
    }
  } else if (model.task === "ocr-text-recognition") {
    const isTransformerOcr = model.modelId.includes("trocr") || [...fileNames].some((n) => n.includes("encoder"));
    if (isTransformerOcr) {
      const hasEncoder = [...fileNames].some((n) => n.includes("encoder") && n.endsWith(".onnx"));
      const hasDecoder = [...fileNames].some((n) => n.includes("decoder") && n.endsWith(".onnx"));
      if (!hasEncoder || !hasDecoder) {
        throw new Error(
          `SEMANTIC_MODEL_INVALID: Transformer OCR task for '${model.modelId}' requires encoder and decoder ONNX models`,
        );
      }
    } else {
      const hasDet = fileNames.has("det.onnx") || [...fileNames].some((n) => n.includes("det") && n.endsWith(".onnx"));
      const hasRec = fileNames.has("rec.onnx") || [...fileNames].some((n) => n.includes("rec") && n.endsWith(".onnx"));
      if (!hasDet || !hasRec) {
        throw new Error(
          `SEMANTIC_MODEL_INVALID: Task 'ocr-text-recognition' for '${model.modelId}' requires detector (det.onnx) and recognizer (rec.onnx)`,
        );
      }
    }
  } else if (model.task === "ui-segmentation") {
    const hasOnnx = [...fileNames].some((n) => n.endsWith(".onnx"));
    if (!hasOnnx) {
      throw new Error(
        `SEMANTIC_MODEL_INVALID: Task 'ui-segmentation' for '${model.modelId}' requires an ONNX model`,
      );
    }
  }

  // 2. Recognizer Capability and Language Claims
  const capId = (model as any).recognizerCapabilityId || (prov as any)?.recognizerCapabilityId;
  if (capId) {
    const cap = RECOGNIZER_CAPABILITIES[capId];
    if (!cap) {
      throw new Error(
        `SEMANTIC_MODEL_INVALID: Unknown recognizerCapabilityId '${capId}' for model '${model.modelId}'`,
      );
    }

    // Verify language claims match capability
    const allowedLangs = new Set(cap.supportedLanguages.map((l) => l.toLowerCase()));
    for (const lang of model.supportedLanguages) {
      if (!allowedLangs.has(lang.toLowerCase())) {
        throw new Error(
          `SEMANTIC_MODEL_INVALID: Model '${model.modelId}' claims language '${lang}' not supported by recognizer capability '${capId}' (supported: ${cap.supportedLanguages.join(", ")})`,
        );
      }
    }

    // 3. Dictionary matches recognizer
    const dictFile = cap.dictionaryArtifact.split("/").pop();
    if (dictFile && !fileNames.has(dictFile)) {
      throw new Error(
        `SEMANTIC_MODEL_INVALID: Model '${model.modelId}' missing dictionary '${dictFile}' required by capability '${capId}'`,
      );
    }

    // Check specific script recognizer artifacts if provenance or files specify upstreamUrl
    if (prov && "files" in prov) {
      const recProvFile = prov.files.find((f: any) => f.name === "rec.onnx" || f.name.endsWith("rec.onnx"));
      if (recProvFile && "upstreamUrl" in recProvFile) {
        if (!recProvFile.upstreamUrl.includes(cap.upstreamArtifact)) {
          throw new Error(
            `SEMANTIC_MODEL_INVALID: Recognizer artifact in provenance '${recProvFile.upstreamUrl}' does not match capability artifact '${cap.upstreamArtifact}'`,
          );
        }
      }
      const dictProvFile = prov.files.find((f: any) => f.name === "dict.txt" || f.name.endsWith("dict.txt"));
      if (dictProvFile && "upstreamUrl" in dictProvFile) {
        if (!dictProvFile.upstreamUrl.includes(cap.dictionaryArtifact)) {
          throw new Error(
            `SEMANTIC_MODEL_INVALID: Dictionary artifact in provenance '${dictProvFile.upstreamUrl}' does not match capability dictionary '${cap.dictionaryArtifact}'`,
          );
        }
      }

      // 4. Detector/recognizer version pairing
      const detProvFile = prov.files.find((f: any) => f.name === "det.onnx" || f.name.endsWith("det.onnx"));
      if (detProvFile && "upstreamUrl" in detProvFile) {
        if (cap.detectorVersion === "v3" && detProvFile.upstreamUrl.includes("detection/v5/")) {
          throw new Error(
            `SEMANTIC_MODEL_INVALID: Incompatible detector/recognizer version pairing: v5 detector cannot be paired with v3 recognizer for '${model.modelId}'`,
          );
        }
        if (cap.detectorVersion === "v5" && detProvFile.upstreamUrl.includes("detection/v3/")) {
          throw new Error(
            `SEMANTIC_MODEL_INVALID: Incompatible detector/recognizer version pairing: v3 detector cannot be paired with v5 recognizer for '${model.modelId}'`,
          );
        }
      }
    }
  } else if (model.task === "ocr-text-recognition") {
    // If it's an OCR model without recognizerCapabilityId, reject if it claims specific non-Latin scripts
    const nonLatin = ["hi", "te", "ta", "bn", "mr", "gu", "kn", "ml", "pa", "zh", "ja", "ko", "ar"];
    const claimedNonLatin = model.supportedLanguages.filter((l) => nonLatin.includes(l.toLowerCase()));
    if (claimedNonLatin.length > 0) {
      throw new Error(
        `SEMANTIC_MODEL_INVALID: Model '${model.modelId}' claims scripts/languages [${claimedNonLatin.join(", ")}] without a verified recognizerCapabilityId binding`,
      );
    }
  }
}

/**
 * Validates license provenance, ensuring base model licenses are not mislabeled and
 * unverified conversion licenses fail closed.
 */
export function validateLicenseProvenance(prov: UpstreamModelProvenance): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];
  if (prov.baseModel?.includes("whisper") && prov.baseModelLicense !== "MIT") {
    errors.push(
      `LICENSE_MISMATCH: Whisper base model is MIT, but baseModelLicense was mislabeled as '${prov.baseModelLicense}'`,
    );
  }
  if (
    prov.conversionRepoLicense === "UNVERIFIED" &&
    prov.artifactLicenseStatus === "VERIFIED_APACHE_2_0"
  ) {
    errors.push(
      `UNVERIFIED_LICENSE_PROMOTION: Cannot claim VERIFIED_APACHE_2_0 when conversion repo license is UNVERIFIED`,
    );
  }
  if (prov.license?.includes("UNKNOWN") || prov.license?.includes("INFERRED")) {
    errors.push(`UNKNOWN_LICENSE: License must fail closed: '${prov.license}'`);
  }
  return { valid: errors.length === 0, errors };
}

/**
 * Asserts that a provenance claim is backed by live authoritative verification.
 */
export function assertLiveSourceVerified(prov: {
  verificationTier?: string;
  isLiveVerified?: boolean;
}): void {
  if (prov.verificationTier !== "LIVE_SOURCE_VERIFIED" || !prov.isLiveVerified) {
    throw new Error(
      "EPISTEMIC VIOLATION: Offline cached metadata cannot claim LIVE_SOURCE_VERIFIED without live authoritative Hugging Face API verification",
    );
  }
}

/**
 * Checks if a git commit revision is patterned or fabricated rather than genuine.
 */
export function isPatternedRevision(rev: string): boolean {
  if (!rev || typeof rev !== "string") return true;
  const r = rev.toLowerCase().trim();
  if (r.length !== 40 && r.length !== 64) return true;
  if (!/^[0-9a-f]+$/.test(r)) return true;
  if (r.includes("0123456789abcdef")) return true;
  if (/a1b2c3d4|a6b8c9d0|b7c8d9e0|c8d9e0f1|d9e0f1a2|e4f5a6b7|1a2b3c4d|2b3c4d5e|9a0b1c2d|8f901234/.test(r)) return true;
  if (/^(.)\1{15,}/.test(r)) return true;
  if (/^0{40}$|^f{40}$/.test(r)) return true;
  return false;
}

/**
 * Validates upstream model provenance against verified repository commits and files.
 */
export function validateUpstreamProvenance(prov: UpstreamModelProvenance): {
  valid: boolean;
  errors: string[];
  verificationTier: ProvenanceVerificationTier;
  isLiveVerified: boolean;
} {
  const errors: string[] = [];
  if (!prov) {
    return {
      valid: false,
      errors: ["Missing upstream provenance record"],
      verificationTier: "UNVERIFIED",
      isLiveVerified: false,
    };
  }

  // Revision validation
  if (isPatternedRevision(prov.revision)) {
    errors.push(`Patterned, fake, or synthetic revision rejected: ${prov.revision}`);
  }

  // Repository verification against cached allowlist
  const repoEntry = CACHED_VERIFIED_UPSTREAM_METADATA[prov.upstreamRepository];
  if (!repoEntry) {
    errors.push(
      `Unverified or nonexistent repository rejected: ${prov.upstreamRepository}`,
    );
  } else {
    // Verified revision check
    const revEntry = repoEntry.verifiedRevisions[prov.revision];
    if (!revEntry) {
      errors.push(
        `Nonexistent revision, invalid revision, or unverified commit for repository: ${prov.revision}`,
      );
    } else {
      // Upstream file membership verification
      for (const f of prov.files || []) {
        const verifiedFile = revEntry.files[f.name];
        if (!verifiedFile) {
          errors.push(
            `Unknown or unverified file '${f.name}' missing from upstream verified revision ${prov.revision}`,
          );
        }
      }
    }
  }

  // License verification
  if (
    !prov.license ||
    prov.license.toUpperCase().includes("UNKNOWN") ||
    prov.license.toUpperCase().includes("INFERRED")
  ) {
    errors.push(`Invalid, unverified, or inferred license rejected: ${prov.license}`);
  }

  // Epistemic honesty check: cached allowlist cannot claim live verification
  if (prov.isLiveVerified === true || prov.verificationTier === "LIVE_SOURCE_VERIFIED") {
    errors.push(
      `EPISTEMIC VIOLATION: Offline cached metadata cannot claim LIVE_SOURCE_VERIFIED without live network proof`,
    );
  }

  return {
    valid: errors.length === 0,
    errors,
    verificationTier: errors.length === 0 ? "CACHED_SOURCE_VERIFIED" : "UNVERIFIED",
    isLiveVerified: false,
  };
}

/**
 * Checks if a byte buffer contains a Git LFS pointer text file instead of actual binary payload.
 */
export function isGitLfsPointer(bytes: Uint8Array): boolean {
  if (!bytes || bytes.length === 0 || bytes.length > 512) return false;
  try {
    const text = new TextDecoder().decode(bytes);
    return (
      text.startsWith("version https://git-lfs.github.com/spec/v1") &&
      text.includes("oid sha256:")
    );
  } catch {
    return false;
  }
}

/**
 * Verifies raw artifact bytes against expected SHA-256 digest and size,
 * strictly rejecting Git LFS pointer text files.
 */
export function verifyArtifactBytes(
  bytes: Uint8Array,
  expectedSha256: string,
  expectedSize?: number,
): boolean {
  if (!bytes || bytes.length === 0) {
    throw new Error("DIGEST_MISMATCH: Empty or zero-byte artifact buffer");
  }
  if (isGitLfsPointer(bytes)) {
    throw new Error(
      "LFS_POINTER_REJECTED: Git LFS pointer text file cannot be accepted as model binary payload",
    );
  }
  if (expectedSize !== undefined && bytes.length !== expectedSize) {
    throw new Error(
      `DIGEST_MISMATCH: Byte size mismatch: expected ${expectedSize}, got ${bytes.length}`,
    );
  }
  const actualSha = computeSha256(bytes);
  if (actualSha.toLowerCase() !== expectedSha256.toLowerCase()) {
    throw new Error(
      `DIGEST_MISMATCH: SHA-256 mismatch: expected ${expectedSha256}, got ${actualSha}`,
    );
  }
  return true;
}

/**
 * Enforces that estimated file sizes are not reported as measured unless
 * binary custody has been verified.
 */
export function assertMeasuredSize(file: {
  name?: string;
  expectedSizeBytes: number;
  isRealBinaryVerified?: boolean;
}): number {
  if (!file || !file.isRealBinaryVerified) {
    throw new Error(
      `ESTIMATED_SIZE_NOT_MEASURED: File '${file?.name || "unnamed"}' is marked isRealBinaryVerified=false. CUSTODY_UNVERIFIED: Estimated size cannot be treated as measured.`,
    );
  }
  return file.expectedSizeBytes;
}

/**
 * Checks whether an OCR recognizer supports a specified script.
 */
export function isScriptSupportedByRecognizer(
  recognizer: { supportedScripts?: string[] },
  script: string,
): boolean {
  if (!recognizer?.supportedScripts || !Array.isArray(recognizer.supportedScripts)) {
    return false;
  }
  const target = script.toLowerCase().trim();
  return recognizer.supportedScripts.some((s) => s.toLowerCase().trim() === target);
}

/**
 * Asserts that an OCR recognizer supports a specified script, throwing if unsupported.
 */
export function assertScriptSupportedByRecognizer(
  recognizer: { supportedScripts?: string[]; modelId?: string },
  script: string,
): void {
  if (!isScriptSupportedByRecognizer(recognizer, script)) {
    throw new Error(
      `UNSUPPORTED_SCRIPT_FOR_RECOGNIZER: Recognizer '${recognizer?.modelId || "unspecified"}' does not support script '${script}'. Supported scripts: ${recognizer?.supportedScripts?.join(", ") || "none"}`,
    );
  }
}

/**
 * Checks if a hex digest was trivially computed from a string label rather
 * than from actual model artifact file bytes.
 * Epistemic Law: SHA256(string label) != SHA256(real model file)
 */
export function isStringLabelDerivedDigest(sha: string): boolean {
  if (!sha || typeof sha !== "string") return true;
  const s = sha.toLowerCase().trim();
  const testLabels = [
    "whisper-tiny-tokenizer-v1",
    "spe-ocr-multilingual-int8-root-v1",
    "spe-whisper-tiny-int8-root-v1",
    "whisper-tiny-int8",
    "spe-whisper-tiny-int8",
    "mobile-ocr-multilingual-int8",
    "spe-ocr-multilingual-int8",
    "spe-ui-segmenter-int8",
    "spe-ocr-paddle-int8",
    "spe-ocr-trocr-int8",
    "spe-root",
    "model.onnx",
    "test",
    "fixture",
    "synthetic",
  ];
  for (const label of testLabels) {
    if (computeSha256(label).toLowerCase() === s) return true;
    if (computeSha256(`spe-${label}`).toLowerCase() === s) return true;
    if (computeSha256(`${label}-v1`).toLowerCase() === s) return true;
  }
  return false;
}

/**
 * Verifies compatibility of tokenizer asset against model vocabulary requirements.
 * Rejects mismatched, corrupted, or empty tokenizer dictionaries.
 */
export function verifyTokenizerCompatibility(
  modelId: string,
  tokenizerBytes: Uint8Array,
): { compatible: boolean; error?: string } {
  if (!tokenizerBytes || tokenizerBytes.length === 0) {
    throw new Error("TOKENIZER MISMATCH: Empty or missing tokenizer asset");
  }
  try {
    const text = new TextDecoder().decode(tokenizerBytes);
    const json = JSON.parse(text);
    if (!json.model || !json.model.vocab) {
      throw new Error("TOKENIZER MISMATCH: Invalid tokenizer format (missing model.vocab)");
    }
    if (modelId.includes("whisper") && !json.model.vocab["<|startoftranscript|>"]) {
      throw new Error("TOKENIZER MISMATCH: Missing Whisper special tokens in tokenizer vocab");
    }
    return { compatible: true };
  } catch (err) {
    throw new Error(`TOKENIZER MISMATCH: ${(err as Error).message}`);
  }
}

export class ModelPackRegistry {
  private installedPacks = new Map<string, ModelPack>();
  private loadedModelAssets = new Map<string, Record<string, Uint8Array>>();

  constructor() {
    // MM-Q3-R2 Invariant: Assert no stale model identities survive
    assertNoStaleModelIdentities(VETTED_MODEL_MANIFESTS);

    // MM-Q3-R2/R3 Invariants: Cross-validate manifest and provenance alignment & semantic validity
    for (const [modelId, manifest] of Object.entries(VETTED_MODEL_MANIFESTS)) {
      const prov = PRODUCTION_MODEL_PROVENANCE[modelId];
      if (prov) {
        assertManifestProvenanceConsistency(manifest, prov);
      }
      assertSemanticModelValidity(manifest, prov);
    }

    // Initialize vetted packs in NOT_INSTALLED state with decoupled manifest copies
    for (const [modelId, manifest] of Object.entries(VETTED_MODEL_MANIFESTS)) {
      this.installedPacks.set(modelId, {
        manifest: {
          ...manifest,
          files: manifest.files.map((f) => ({ ...f })),
        },
        state: "NOT_INSTALLED",
        provisioning: "EXPLICIT_DOWNLOAD",
        installedBytes: 0,
        activeBackend: "UNAVAILABLE",
        verifiedDigest: null,
        verifiedPayloadDigest: null,
        archiveSha256: null,
        artifactLicenseStatus: manifest.artifactLicenseStatus,
      });
    }
  }

  getPack(modelId: string): ModelPack | null {
    return this.installedPacks.get(modelId) ?? null;
  }

  listPacks(): ModelPack[] {
    return Array.from(this.installedPacks.values());
  }

  getModelAssets(modelId: string): Record<string, Uint8Array> | null {
    return this.loadedModelAssets.get(modelId) ?? null;
  }

  /**
   * Verify SHA-256 digest of provided model asset bytes.
   */
  verifyAssetDigest(bytes: Uint8Array, expectedSha256: string): boolean {
    if (!bytes || bytes.length === 0) return false;
    const calculated = computeSha256(bytes);
    return calculated.toLowerCase() === expectedSha256.toLowerCase();
  }

  /**
   * Validates manifest structure and rejects unsafe, patterned, or unvetted entries.
   */
  validateManifest(manifest: ModelManifest): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    if (!manifest.modelId || typeof manifest.modelId !== "string") {
      errors.push("Missing or invalid modelId");
    }
    if (!manifest.sha256 || manifest.sha256.length !== 64) {
      errors.push("Invalid root sha256 digest (must be 64-char hex)");
    } else if (isPatternedDigest(manifest.sha256)) {
      errors.push(`Patterned or fabricated root digest rejected: ${manifest.sha256}`);
    } else if (isStringLabelDerivedDigest(manifest.sha256)) {
      errors.push(`String-label derived root digest rejected (must be real file hash): ${manifest.sha256}`);
    }
    if (!manifest.license || manifest.license.toUpperCase().includes("UNKNOWN")) {
      errors.push("Unlicensed or unknown license rejected for production pack");
    }
    if (!manifest.files || manifest.files.length === 0) {
      errors.push("Manifest contains no model files");
    }
    if (
      manifest.opsetVersion !== undefined &&
      (manifest.opsetVersion < 11 || manifest.opsetVersion > 19)
    ) {
      errors.push(
        `Unsupported ONNX operator set version: ${manifest.opsetVersion} (supported: 11-19)`,
      );
    }
    const ALLOWED_EXTS = ["onnx", "json", "txt", "bin", "proto", "wasm"];
    for (const f of manifest.files ?? []) {
      if (f.name.includes("..") || f.name.includes("/") || f.name.includes("\\")) {
        errors.push(`Disallowed path traversal in file: ${f.name}`);
      }
      const ext = f.name.toLowerCase().split(".").pop();
      if (!ext || !ALLOWED_EXTS.includes(ext)) {
        errors.push(`Disallowed unknown or executable asset format: ${f.name}`);
      }
      if (!f.sha256 || f.sha256.length !== 64) {
        errors.push(`Invalid sha256 for file: ${f.name}`);
      } else if (isPatternedDigest(f.sha256)) {
        errors.push(`Patterned or fabricated file digest rejected for ${f.name}: ${f.sha256}`);
      } else if (isStringLabelDerivedDigest(f.sha256)) {
        errors.push(`String-label derived file digest rejected for ${f.name} (must be real file hash): ${f.sha256}`);
      }
      if (f.sizeBytes <= 0) {
        errors.push(`Invalid zero or negative sizeBytes for file ${f.name} (must be >0): ${f.sizeBytes}`);
      }
    }
    if (manifest.qualificationState === "QUALIFIED") {
      errors.push(
        `Unverified qualificationState 'QUALIFIED' rejected: Model binary artifacts are not bound on local disk. Must begin as 'DECLARED', 'MANIFEST_ONLY', or 'ARTIFACT_UNVERIFIED'.`,
      );
    }
    return { valid: errors.length === 0, errors };
  }

  /**
   * Explicitly provision a model pack via Download or Sideload.
   * STRICT: Requires user initiation. Throws if digest or size mismatch occurs.
   * REJECTS: Unexpected files, unknown formats, partial downloads, digest corruptions.
   */
  async provisionPack(
    modelId: string,
    mode: ProvisioningMode,
    filesPayload: Record<string, Uint8Array>,
    targetBackend: "WEBGPU" | "WASM" = "WASM",
  ): Promise<ModelPack> {
    const pack = this.installedPacks.get(modelId);
    if (!pack) {
      throw new Error(`Model pack not found in registry: ${modelId}`);
    }

    pack.state = "DOWNLOADING";
    pack.provisioning = mode;

    try {
      pack.state = "VERIFYING";

      // MM-6 Law: Reject unexpected files in payload
      const declaredFileNames = new Set(pack.manifest.files.map((f) => f.name));
      for (const fileName of Object.keys(filesPayload)) {
        if (!declaredFileNames.has(fileName)) {
          throw new Error(`Security rejection: unexpected file in payload: ${fileName}`);
        }
      }

      let totalBytes = 0;

      for (const reqFile of pack.manifest.files) {
        const fileBytes = filesPayload[reqFile.name];
        if (!fileBytes) {
          if (reqFile.required) {
            throw new Error(`Missing required model asset: ${reqFile.name}`);
          }
          continue;
        }

        if (fileBytes.length === 0) {
          throw new Error(`Zero-byte model asset rejected for ${reqFile.name}`);
        }

        if (isGitLfsPointer(fileBytes)) {
          throw new Error(
            `LFS_POINTER_REJECTED: Model asset '${reqFile.name}' is a Git LFS pointer text file, not a model binary payload`,
          );
        }

        // Check for partial download (size mismatch)
        if (reqFile.sizeBytes > 0 && fileBytes.length !== reqFile.sizeBytes) {
          throw new Error(
            `Asset size mismatch for ${reqFile.name}: expected ${reqFile.sizeBytes} bytes, got ${fileBytes.length} bytes (partial download detected)`,
          );
        }

        const valid = this.verifyAssetDigest(fileBytes, reqFile.sha256);
        if (!valid) {
          throw new Error(
            `Digest mismatch on asset ${reqFile.name}: expected ${reqFile.sha256}`,
          );
        }
        totalBytes += fileBytes.length;
      }

      // Store verified file assets in memory for local inference
      this.loadedModelAssets.set(modelId, { ...filesPayload });

      const payloadSha256 = computePayloadSha256(filesPayload);
      pack.installedBytes = totalBytes;
      pack.verifiedPayloadDigest = payloadSha256;
      pack.verifiedDigest = payloadSha256;
      pack.artifactLicenseStatus = pack.manifest.artifactLicenseStatus;
      pack.activeBackend = targetBackend;
      pack.state = "READY";
      pack.installedAt = new Date().toISOString();
      return pack;
    } catch (err) {
      pack.state = "FAILED";
      pack.errorMessage = (err as Error).message;
      throw err;
    }
  }

  /**
   * Sideloads an offline packaged archive directly into the registry.
   */
  async sideloadPack(
    archiveBytes: Uint8Array,
    targetBackend: "WEBGPU" | "WASM" = "WASM",
  ): Promise<{
    modelId: string;
    status: "INSTALLED" | "FAILED";
    pack: ModelPack;
    rawUserDataEgress: 0;
  }> {
    const pkg = unpackModelArchive(archiveBytes);
    let pack = this.installedPacks.get(pkg.modelId);
    if (!pack) {
      pack = {
        manifest: pkg.manifest,
        state: "NOT_INSTALLED",
        provisioning: "OFFLINE_SIDELOAD",
        installedBytes: 0,
        activeBackend: "UNAVAILABLE",
        verifiedDigest: null,
        verifiedPayloadDigest: pkg.payloadSha256 || pkg.archiveDigest,
        archiveSha256: pkg.archiveSha256,
        artifactLicenseStatus: pkg.manifest.artifactLicenseStatus,
        artifactClass: pkg.artifactClass,
        productionQualificationAllowed: pkg.productionQualificationAllowed,
      };
      this.installedPacks.set(pkg.modelId, pack);
    } else {
      pack.manifest = pkg.manifest;
      pack.artifactClass = pkg.artifactClass;
      pack.productionQualificationAllowed = pkg.productionQualificationAllowed;
      pack.artifactLicenseStatus = pkg.manifest.artifactLicenseStatus;
    }

    await this.provisionPack(pkg.modelId, "OFFLINE_SIDELOAD", pkg.files, targetBackend);
    pack.archiveSha256 = pkg.archiveSha256;
    pack.verifiedPayloadDigest = pkg.payloadSha256 || pack.verifiedPayloadDigest;
    pack.verifiedDigest = pack.verifiedPayloadDigest || null;
    this.loadedModelAssets.set(pkg.modelId, { ...pkg.files });

    return {
      modelId: pkg.modelId,
      status: "INSTALLED",
      pack,
      rawUserDataEgress: 0,
    };
  }

  /**
   * Assert production qualification readiness; strictly fails closed if synthetic or fixture-only.
   */
  assertProductionQualified(modelId: string): void {
    const pack = this.installedPacks.get(modelId);
    if (!pack || pack.state !== "READY") {
      throw new Error(`Model ${modelId} is not installed or ready.`);
    }
    if (pack.artifactClass === "TEST_FIXTURE" || !pack.productionQualificationAllowed) {
      throw new Error(
        `PRODUCTION_QUALIFICATION_REJECTED: Model ${modelId} is a TEST_FIXTURE. Synthetic model assets cannot receive qualified status.`,
      );
    }

    // License Check: Reject HOLD or UNVERIFIED license status
    const prov = PRODUCTION_MODEL_PROVENANCE[modelId];
    const licenseStatus =
      pack.artifactLicenseStatus ||
      pack.manifest.artifactLicenseStatus ||
      prov?.artifactLicenseStatus;
    if (licenseStatus === "HOLD" || licenseStatus === "UNVERIFIED" || !licenseStatus) {
      throw new Error(
        `PRODUCTION_QUALIFICATION_REJECTED: ARTIFACT_LICENSE_UNRESOLVED: Model ${modelId} has artifactLicenseStatus='${licenseStatus || "UNRESOLVED"}'. Base-model license alone is insufficient.`,
      );
    }

    // Verified Digest Check: Must have a valid verified payload digest
    const verifiedPayloadSha = pack.verifiedPayloadDigest || pack.verifiedDigest;
    if (!verifiedPayloadSha) {
      throw new Error(
        `PRODUCTION_QUALIFICATION_REJECTED: Model ${modelId} lacks a verified payload digest.`,
      );
    }

    if (isStringLabelDerivedDigest(verifiedPayloadSha) || isStringLabelDerivedDigest(pack.manifest.sha256)) {
      throw new Error(
        `PRODUCTION_QUALIFICATION_REJECTED: String-label derived digest detected in model ${modelId}. Must be cryptographically computed from actual model binary bytes.`,
      );
    }
    if (pack.manifest.qualificationState !== "QUALIFIED" && pack.manifest.qualificationState !== "INFERENCE_VERIFIED") {
      throw new Error(
        `PRODUCTION_QUALIFICATION_REJECTED: Model ${modelId} manifest state is '${pack.manifest.qualificationState}'. Real external model binary required for production qualification.`,
      );
    }
  }

  /**
   * Uninstall / drop model pack from memory.
   */
  evictPack(modelId: string): void {
    const pack = this.installedPacks.get(modelId);
    if (pack) {
      pack.state = "NOT_INSTALLED";
      pack.installedBytes = 0;
      pack.activeBackend = "UNAVAILABLE";
      pack.verifiedDigest = null;
    }
    this.loadedModelAssets.delete(modelId);
  }
}

/**
 * Checks if a 64-char hex digest is patterned or fabricated rather than cryptographically computed.
 */
export function isPatternedDigest(sha: string): boolean {
  if (!sha || typeof sha !== "string") return true;
  const s = sha.toLowerCase().trim();
  if (s.length !== 64 || !/^[0-9a-f]{64}$/.test(s)) return true;
  // Repetitive or sequential hex patterns
  if (s.includes("0123456789abcdef")) return true;
  if (/a1b2c3d4|b4c5d6e7|e4f5a6b7|1a2b3c4d|2b3c4d5e|9a0b1c2d|8f901234/.test(s)) return true;
  if (/^(.)\1{15,}/.test(s)) return true;
  return false;
}

/**
 * Binary container format for offline model packs (.spemodel):
 * [0..7] ASCII "SPEMODEL"
 * [8..11] formatVersion uint32 (1)
 * [12..15] headerLength uint32
 * [16..16+headerLength-1] UTF-8 JSON header string
 * [16+headerLength..] Binary payload of concatenated files
 */
export function packModelArchive(
  manifest: ModelManifest,
  files: Record<string, Uint8Array>,
  options?: {
    artifactClass?: "PRODUCTION_RELEASE" | "TEST_FIXTURE";
    productionQualificationAllowed?: boolean;
  },
): Uint8Array {
  const encoder = new TextEncoder();
  const fileEntries: Record<string, { offset: number; length: number; sha256: string }> = {};

  const sortedNames = Object.keys(files).sort();
  let currentOffset = 0;
  const fileBuffers: Uint8Array[] = [];

  for (const name of sortedNames) {
    const bytes = files[name];
    const fileSha = computeSha256(bytes);
    fileEntries[name] = {
      offset: currentOffset,
      length: bytes.length,
      sha256: fileSha,
    };
    fileBuffers.push(bytes);
    currentOffset += bytes.length;
  }

  // Concatenate all file bytes in deterministic lexicographical order to compute payload digest
  const combinedPayload = new Uint8Array(currentOffset);
  let pOffset = 0;
  for (const b of fileBuffers) {
    combinedPayload.set(b, pOffset);
    pOffset += b.length;
  }
  const payloadSha256 = computeSha256(combinedPayload);
  const archiveDigest = payloadSha256;
  const manifestDigest = manifest.manifestDigest || computeManifestDigest(manifest);

  const artifactClass = options?.artifactClass || "TEST_FIXTURE";
  const productionQualificationAllowed =
    artifactClass === "TEST_FIXTURE" ? false : Boolean(options?.productionQualificationAllowed);

  const headerObj = {
    magic: "SPEMODEL",
    formatVersion: 1,
    modelId: manifest.modelId,
    manifest: {
      ...manifest,
      manifestDigest,
      expectedPayloadSha256: payloadSha256,
      sha256: manifestDigest,
    },
    filesMap: fileEntries,
    archiveDigest,
    payloadSha256,
    manifestDigest,
    packagedAt: new Date().toISOString(),
    artifactClass,
    productionQualificationAllowed,
  };

  const headerJson = JSON.stringify(headerObj);
  const headerBytes = encoder.encode(headerJson);

  const totalLength = 16 + headerBytes.length + combinedPayload.length;
  const out = new Uint8Array(totalLength);
  const view = new DataView(out.buffer, out.byteOffset, out.byteLength);

  // Magic: "SPEMODEL"
  out.set(encoder.encode("SPEMODEL"), 0);

  // Version: 1
  view.setUint32(8, 1, false);

  // Header length
  view.setUint32(12, headerBytes.length, false);

  // Header JSON
  out.set(headerBytes, 16);

  // Payload
  out.set(combinedPayload, 16 + headerBytes.length);

  return out;
}

export function unpackModelArchive(archiveBytes: Uint8Array): OfflineModelPackage {
  if (archiveBytes.length < 16) {
    throw new Error("Invalid model package: payload too small (<16 bytes)");
  }
  const decoder = new TextDecoder();
  const magic = decoder.decode(archiveBytes.subarray(0, 8));
  if (magic !== "SPEMODEL") {
    throw new Error(`Invalid model package magic signature: '${magic}', expected 'SPEMODEL'`);
  }

  const view = new DataView(archiveBytes.buffer, archiveBytes.byteOffset, archiveBytes.byteLength);
  const version = view.getUint32(8, false);
  if (version !== 1) {
    throw new Error(`Unsupported model package format version: ${version} (expected 1)`);
  }

  const headerLength = view.getUint32(12, false);
  if (16 + headerLength > archiveBytes.length) {
    throw new Error("Corrupted model package: header length exceeds total buffer size");
  }

  const headerJson = decoder.decode(archiveBytes.subarray(16, 16 + headerLength));
  let header: {
    modelId: string;
    manifest: ModelManifest;
    filesMap: Record<string, { offset: number; length: number; sha256: string }>;
    archiveDigest: string;
    payloadSha256?: string;
    manifestDigest?: string;
    packagedAt: string;
    artifactClass?: "PRODUCTION_RELEASE" | "TEST_FIXTURE";
    productionQualificationAllowed?: boolean;
  };

  try {
    header = JSON.parse(headerJson);
  } catch (err) {
    throw new Error(`Corrupted model package header JSON: ${(err as Error).message}`);
  }

  const payloadOffset = 16 + headerLength;
  const files: Record<string, Uint8Array> = {};

  for (const [name, meta] of Object.entries(header.filesMap)) {
    const start = payloadOffset + meta.offset;
    const end = start + meta.length;
    if (end > archiveBytes.length) {
      throw new Error(`Corrupted model asset '${name}': range [${start}, ${end}] exceeds package length`);
    }
    const fileBytes = archiveBytes.subarray(start, end);
    if (fileBytes.length === 0) {
      throw new Error(`Zero-byte model asset rejected for '${name}' in package`);
    }
    const calculatedSha = computeSha256(fileBytes);
    if (calculatedSha.toLowerCase() !== meta.sha256.toLowerCase()) {
      throw new Error(`Digest mismatch for model asset '${name}' in package: expected ${meta.sha256}`);
    }
    files[name] = fileBytes;
  }

  const computedPayloadSha = computePayloadSha256(files);
  const expectedPayloadSha = header.payloadSha256 || header.archiveDigest;
  if (expectedPayloadSha && computedPayloadSha.toLowerCase() !== expectedPayloadSha.toLowerCase()) {
    throw new Error(
      `Corrupted model package: payload SHA mismatch: expected ${expectedPayloadSha}, got ${computedPayloadSha}`,
    );
  }

  // Anti-fraud gate: 512-byte synthetic model.onnx can never receive production qualification
  let artifactClass = header.artifactClass || "TEST_FIXTURE";
  let productionQualificationAllowed =
    artifactClass === "TEST_FIXTURE" ? false : Boolean(header.productionQualificationAllowed);

  if (header.filesMap["model.onnx"]?.length === 512) {
    artifactClass = "TEST_FIXTURE";
    productionQualificationAllowed = false;
  }

  return {
    magic: "SPEMODEL",
    formatVersion: 1,
    modelId: header.modelId,
    manifest: header.manifest,
    files,
    archiveDigest: header.archiveDigest,
    payloadSha256: computedPayloadSha,
    archiveSha256: computeArchiveSha256(archiveBytes),
    manifestDigest: header.manifestDigest || header.manifest?.manifestDigest,
    packagedAt: header.packagedAt,
    artifactClass,
    productionQualificationAllowed,
  };
}

export const TEST_ONLY_SYNTHETIC_MODEL_PACKAGE = true;

/**
 * Creates a synthetic in-memory model package STRICTLY FOR UNIT TESTING container logic.
 * INVARIANT: Must NEVER be accepted as production qualification evidence.
 */
export function generateSyntheticModelFixturePackage(modelId: string): Uint8Array {
  const manifest = VETTED_MODEL_MANIFESTS[modelId];
  if (!manifest) {
    throw new Error(`No vetted manifest found for modelId: ${modelId}`);
  }

  // Clone manifest so we don't mutate global constants permanently
  const clonedManifest: ModelManifest = JSON.parse(JSON.stringify(manifest));
  clonedManifest.qualificationState = "ARTIFACT_UNVERIFIED";
  const files: Record<string, Uint8Array> = {};

  for (const f of clonedManifest.files) {
    const size = f.sizeBytes > 0 ? Math.min(f.sizeBytes, 1024) : 64;
    const synthetic = new Uint8Array(size);
    for (let i = 0; i < synthetic.length; i++) {
      synthetic[i] = (i * 37 + 13) % 256;
    }
    f.sha256 = computeSha256(synthetic);
    f.sizeBytes = synthetic.length;
    files[f.name] = synthetic;
  }
  if (!files["model.onnx"]) {
    const modelBytes = new Uint8Array(512);
    for (let i = 0; i < modelBytes.length; i++) modelBytes[i] = (i * 17) % 256;
    const modelSha = computeSha256(modelBytes);
    clonedManifest.files.push({
      name: "model.onnx",
      sizeBytes: modelBytes.length,
      sha256: modelSha,
      required: false,
    });
    files["model.onnx"] = modelBytes;
  }

  clonedManifest.manifestDigest = computeManifestDigest(clonedManifest);
  clonedManifest.expectedPayloadSha256 = computePayloadSha256(files);
  clonedManifest.sha256 = clonedManifest.manifestDigest;

  return packModelArchive(clonedManifest, files, {
    artifactClass: "TEST_FIXTURE",
    productionQualificationAllowed: false,
  });
}

export const generateVettedOfflinePackage = generateSyntheticModelFixturePackage;
export const generateTestOnlySyntheticModelPackage = generateSyntheticModelFixturePackage;

export const globalModelRegistry = new ModelPackRegistry();
export { ModelPackRegistry as ModelRegistry };

export function getModelAssets(modelId: string): Record<string, Uint8Array> | null {
  return globalModelRegistry.getModelAssets(modelId);
}

export function sideloadPack(
  archiveBytes: Uint8Array,
  targetBackend: "WEBGPU" | "WASM" = "WASM",
) {
  return globalModelRegistry.sideloadPack(archiveBytes, targetBackend);
}
