"""Canonical K5 typed error registry.

Single owner for all wire reason codes. XCAT ReasonCode and PortabilityReason
are aliases of ErrorCode (same object identity). Wire strings are stable.
"""

from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    # XCAT / category codes (wire strings unchanged)
    CONSTRAINT_WEAKENED = "X01_CONSTRAINT_WEAKENED"
    PROVENANCE_LOST = "X02_PROVENANCE_LOST"
    UNCERTAINTY_ERASED = "X03_UNCERTAINTY_ERASED"
    PREFERENCE_MUTATED = "X04_PREFERENCE_MUTATED"
    FACT_MISSING_PROVENANCE = "X05_FACT_MISSING_PROVENANCE"
    ANALYSIS_AS_RECOMMENDATION = "X06_ANALYSIS_AS_RECOMMENDATION"
    RECOMMENDATION_AS_EXECUTION = "X07_RECOMMENDATION_AS_EXECUTION"
    SEMANTIC_REWRITE = "X08_SEMANTIC_REWRITE"
    AUTHORITY_SELF_ESCALATION = "X09_AUTHORITY_SELF_ESCALATION"
    FAILURE_LAUNDERED = "X10_FAILURE_LAUNDERED"
    TAINT_LOST = "X_TAINT_LOST"
    SENSITIVITY_LOST = "X_SENSITIVITY_LOST"
    INVALID_CATEGORY = "X_INVALID_CATEGORY"
    CATEGORY_OWNERSHIP = "X_CATEGORY_OWNERSHIP"
    UNKNOWN = "X_UNKNOWN"
    # Sprint 3 — C07 / authority
    EXECUTION_MISSING_AUTHORITY = "C07_EXECUTION_MISSING_AUTHORITY"
    SCOPE_MISMATCH = "C07_SCOPE_MISMATCH"
    TARGET_DRIFT = "C07_TARGET_DRIFT"
    ARGUMENT_DRIFT = "C07_ARGUMENT_DRIFT"
    AUTHORITY_EXPIRED = "C07_AUTHORITY_EXPIRED"
    AUTHORITY_REVOKED = "C07_AUTHORITY_REVOKED"
    AUTHORITY_CONSUMED = "C07_AUTHORITY_CONSUMED"
    DECISION_DRIFT = "C07_DECISION_DRIFT"
    OPERATION_ID_REPLACED = "C07_OPERATION_ID_REPLACED"
    UNKNOWN_OUTCOME_RETRY = "C07_UNKNOWN_OUTCOME_RETRY"
    PARTIAL_TO_SUCCESS = "C07_PARTIAL_TO_SUCCESS"
    TOOL_SUCCESS_TO_OUTCOME = "C07_TOOL_SUCCESS_TO_OUTCOME"
    SANDBOX_ESCAPE = "C07_SANDBOX_ESCAPE"
    DUPLICATE_EFFECT = "C07_DUPLICATE_EFFECT"
    GRANT_CONSUME_REFUSED = "C07_GRANT_CONSUME_REFUSED"
    # Portability-specific
    CAPABILITY_MISSING = "P_CAPABILITY_MISSING"
    CAPABILITY_BLOCKED = "P_CAPABILITY_BLOCKED"
    CAPABILITY_DEFER = "P_CAPABILITY_DEFER"
    CAPABILITY_ESCALATION = "P_CAPABILITY_ESCALATION"
    ROUND_TRIP_FAIL = "P_ROUND_TRIP_FAIL"
    CANONICAL_DRIFT = "P_CANONICAL_DRIFT"
    TUPLE_LEAK = "P_TUPLE_LEAK"
    PRIVACY_ESCALATION = "P_PRIVACY_ESCALATION"
    TRUST_ESCALATION = "P_TRUST_ESCALATION"
    AUTHORITY_ESCALATION = "P_AUTHORITY_ESCALATION"
    OUTCOME_ESCALATION = "P_OUTCOME_ESCALATION"
    OPERATION_ID_MUTATION = "P_OPERATION_ID_MUTATION"
    NETWORK_FORBIDDEN = "P_NETWORK_FORBIDDEN"
    FAKE_PLATFORM_STATUS = "P_FAKE_PLATFORM_STATUS"
    ABI_MISMATCH = "P_ABI_MISMATCH"
    SCHEMA_INVALID = "P_SCHEMA_INVALID"
    OFFLINE_VIOLATION = "P_OFFLINE_VIOLATION"
    UNKNOWN_NULLIFIED = "P_UNKNOWN_NULLIFIED"
    HARD_TO_PREFERENCE = "P_HARD_TO_PREFERENCE"
    DENIED_TO_GRANTED = "P_DENIED_TO_GRANTED"
    PROVENANCE_REMOVED = "P_PROVENANCE_REMOVED"
    SEMANTIC_NONEQUIVALENT = "P_SEMANTIC_NONEQUIVALENT"
    UNKNOWN_FIELD_POLICY = "P_UNKNOWN_FIELD_POLICY"
    STATUS_COLLAPSE = "P_STATUS_COLLAPSE"
    # G1R-2 — K4 ambient authority mutation
    GENERIC_AUTHORITY_MUTATION = "K4_GENERIC_AUTHORITY_MUTATION"
    # G1R-3 — K0/K1 semantic foundation
    K0_INVALID_PROVENANCE_TRANSITION = "K0_INVALID_PROVENANCE_TRANSITION"
    K1_INVALID_REQUIREMENT = "K1_INVALID_REQUIREMENT"
    # G1R-4 — K2 proof transaction
    K2_STALE_PATCH = "K2_STALE_PATCH"
    K2_INVALID_SEMANTIC_LEASE = "K2_INVALID_SEMANTIC_LEASE"
    K2_MISSING_PROOF_OBLIGATION = "K2_MISSING_PROOF_OBLIGATION"
    K2_PROOF_TYPE_MISMATCH = "K2_PROOF_TYPE_MISMATCH"
    K2_VERIFICATION_FAILED = "K2_VERIFICATION_FAILED"
    K2_ATOMIC_COMMIT_REJECTED = "K2_ATOMIC_COMMIT_REJECTED"
    # G1R-5 — K4 privacy projection
    K4_PRIVACY_CONFLICT = "K4_PRIVACY_CONFLICT"
    K4_PRIVACY_INVALID_DIRECTIVE = "K4_PRIVACY_INVALID_DIRECTIVE"
    K4_PRIVACY_INVALID_SCOPE = "K4_PRIVACY_INVALID_SCOPE"
    K4_PRIVACY_PROJECTION_FAILED = "K4_PRIVACY_PROJECTION_FAILED"
    # G1R-6 — K3 PromptArtifact
    K3_PROMPT_INVALID_INPUT = "K3_PROMPT_INVALID_INPUT"
    K3_PROMPT_CONFLICTED_SOURCE = "K3_PROMPT_CONFLICTED_SOURCE"
    K3_PROMPT_INVARIANT_VIOLATION = "K3_PROMPT_INVARIANT_VIOLATION"
    # G1R-7 — K3 strategy intelligence
    K3_STRATEGY_INVALID_INPUT = "K3_STRATEGY_INVALID_INPUT"
    K3_STRATEGY_CONFLICTED_SOURCE = "K3_STRATEGY_CONFLICTED_SOURCE"
    K3_STRATEGY_INVARIANT_VIOLATION = "K3_STRATEGY_INVARIANT_VIOLATION"
    K3_TECHNIQUE_INCOMPATIBLE = "K3_TECHNIQUE_INCOMPATIBLE"
    # G1R-8 — K6 .spe semantic artifact + lineage
    K6_INVALID_ARTIFACT = "K6_INVALID_ARTIFACT"
    K6_ARTIFACT_ID_MISMATCH = "K6_ARTIFACT_ID_MISMATCH"
    K6_INVALID_LINEAGE = "K6_INVALID_LINEAGE"
    K6_SNAPSHOT_BINDING_MISMATCH = "K6_SNAPSHOT_BINDING_MISMATCH"
    K6_UNSUPPORTED_ARTIFACT_VERSION = "K6_UNSUPPORTED_ARTIFACT_VERSION"
    # G1R-9 — K7 claim qualification + qualification evidence
    K7_INVALID_EVIDENCE = "K7_INVALID_EVIDENCE"
    K7_SCOPE_MISMATCH = "K7_SCOPE_MISMATCH"
    K7_UNSUPPORTED_CLAIM = "K7_UNSUPPORTED_CLAIM"
    K7_INVALID_POLICY = "K7_INVALID_POLICY"
    K7_EVIDENCE_CONTRADICTION = "K7_EVIDENCE_CONTRADICTION"
    K7_SUBJECT_MISMATCH = "K7_SUBJECT_MISMATCH"


class SpeTypedError(Exception):
    """Typed SPE failure carrying a canonical ErrorCode."""

    def __init__(self, code: ErrorCode, message: str = "") -> None:
        self.code = code
        super().__init__(message or code.value)


__all__ = ["ErrorCode", "SpeTypedError"]
