"""Stable reason codes for XCAT refusals/blocks."""

from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    CONSTRAINT_WEAKENED = "X01_CONSTRAINT_WEAKENED"
    PROVENANCE_LOST = "X02_PROVENANCE_LOST"
    UNCERTAINTY_ERASED = "X03_UNCERTAINTY_ERASED"
    PREFERENCE_MUTATED = "X04_PREFERENCE_MUTATED"
    FACT_MISSING_PROVENANCE = "X05_FACT_MISSING_PROVENANCE"
    ANALYSIS_AS_RECOMMENDATION = "X06_ANALYSIS_AS_RECOMMENDATION"
    RECOMMENDATION_AS_EXECUTION = "X07_RECOMMENDATION_AS_EXECUTION"
    SEMANTIC_REWRITE = "X08_SEMANTIC_REWRITE"
    AUTHORITY_SELF_ESCALATION = "X09_AUTHORITY_SELF_ESCALATION"
    FAILURE_LAUNDERED = "X10_FAILURE_LAUNDERED"
    TAINT_LOST = "X_TAINT_LOST"
    SENSITIVITY_LOST = "X_SENSITIVITY_LOST"
    INVALID_CATEGORY = "X_INVALID_CATEGORY"
    CATEGORY_OWNERSHIP = "X_CATEGORY_OWNERSHIP"
    UNKNOWN = "X_UNKNOWN"
