"""Stable reason codes for XCAT refusals/blocks."""

from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    CONSTRAINT_WEAKENED = "X01_CONSTRAINT_WEAKENED"
    PROVENANCE_LOST = "X02_PROVENANCE_LOST"
    UNCERTAINTY_ERASED = "X03_UNCERTAINTY_ERASED"
    PREFERENCE_MUTATED = "X04_PREFERENCE_MUTATED"
    FACT_MISSING_PROVENANCE = "X05_FACT_MISSING_PROVENANCE"
    ANALYSIS_AS_RECOMMENDATION = "X06_ANALYSIS_AS_RECOMMENDATION"
    RECOMMENDATION_AS_EXECUTION = "X07_RECOMMENDATION_AS_EXECUTION"
    SEMANTIC_REWRITE = "X08_SEMANTIC_REWRITE"
    AUTHORITY_SELF_ESCALATION = "X09_AUTHORITY_SELF_ESCALATION"
    FAILURE_LAUNDERED = "X10_FAILURE_LAUNDERED"
    TAINT_LOST = "X_TAINT_LOST"
    SENSITIVITY_LOST = "X_SENSITIVITY_LOST"
    INVALID_CATEGORY = "X_INVALID_CATEGORY"
    CATEGORY_OWNERSHIP = "X_CATEGORY_OWNERSHIP"
    UNKNOWN = "X_UNKNOWN"
    # Sprint 3 — C07 / authority
    EXECUTION_MISSING_AUTHORITY = "C07_EXECUTION_MISSING_AUTHORITY"
    SCOPE_MISMATCH = "C07_SCOPE_MISMATCH"
    TARGET_DRIFT = "C07_TARGET_DRIFT"
    ARGUMENT_DRIFT = "C07_ARGUMENT_DRIFT"
    AUTHORITY_EXPIRED = "C07_AUTHORITY_EXPIRED"
    AUTHORITY_REVOKED = "C07_AUTHORITY_REVOKED"
    AUTHORITY_CONSUMED = "C07_AUTHORITY_CONSUMED"
    DECISION_DRIFT = "C07_DECISION_DRIFT"
    OPERATION_ID_REPLACED = "C07_OPERATION_ID_REPLACED"
    UNKNOWN_OUTCOME_RETRY = "C07_UNKNOWN_OUTCOME_RETRY"
    PARTIAL_TO_SUCCESS = "C07_PARTIAL_TO_SUCCESS"
    TOOL_SUCCESS_TO_OUTCOME = "C07_TOOL_SUCCESS_TO_OUTCOME"
    SANDBOX_ESCAPE = "C07_SANDBOX_ESCAPE"
    DUPLICATE_EFFECT = "C07_DUPLICATE_EFFECT"
    GRANT_CONSUME_REFUSED = "C07_GRANT_CONSUME_REFUSED"

