/**
 * SPE Ω — Typed Budget Architecture & Length Constraints
 *
 * Distinguishes:
 * 1. SourceBudget: Physical size of user-supplied source document.
 * 2. PromptArtifactBudget: Budget of the prompt generated by SPE.
 * 3. RequestedAnswerBudget: Budget of downstream deliverable requested by prompt.
 * 4. SourceDocument: Authoritative single-source-of-truth representation.
 */
import { countWords, WORD_COUNT_VERSION, type WordCountConvention } from "./wordCount";

export type SourceBudget = {
  source_words: number;
  source_bytes: number;
};

export type PromptArtifactBudget = {
  max_prompt_tokens?: number;
  max_prompt_bytes?: number;
  overflow_policy: "REJECT" | "TRUNCATE_CONTEXT" | "CHUNK";
};

export type BudgetUnit = "words" | "tokens" | "characters" | "sentences";

export type BudgetMode = "exact" | "maximum" | "minimum" | "range" | "approximate";

export type RequestedAnswerBudget = {
  unit: BudgetUnit;
  mode: BudgetMode;
  target: number;
  min?: number;
  max?: number;
  raw_expression?: string;
  counting_contract?: string;
};

export type SourceDocument = {
  id: string;
  raw_text: string;
  sha256: string;
  byte_length: number;
  word_count: number;
};

/**
 * Normalizes Unicode digit characters from multiple scripts (Devanagari, Arabic-Indic, Fullwidth, etc.)
 * to standard ASCII 0-9 digits.
 */
export function normalizeUnicodeDigits(str: string): string {
  return str.replace(/[\u0660-\u0669\u06F0-\u06F9\u0966-\u096F\uFF10-\uFF19]/g, (ch) => {
    const code = ch.charCodeAt(0);
    if (code >= 0x0660 && code <= 0x0669) return String(code - 0x0660); // Arabic-Indic
    if (code >= 0x06f0 && code <= 0x06f9) return String(code - 0x06f0); // Extended Arabic-Indic
    if (code >= 0x0966 && code <= 0x096f) return String(code - 0x0966); // Devanagari
    if (code >= 0xff10 && code <= 0xff19) return String(code - 0xff10); // Fullwidth
    return ch;
  });
}

/**
 * Parses numeric value supporting:
 * - Commas ("20,000")
 * - Underscores ("20_000")
 * - Scientific notation ("2e4")
 * - Unicode digits
 */
export function parseFlexibleNumber(raw: string): number | null {
  if (!raw || typeof raw !== "string") return null;
  let normalized = normalizeUnicodeDigits(raw.trim().replace(/[,_]/g, ""));
  let multiplier = 1;
  if (/[0-9][kK]$/.test(normalized)) {
    multiplier = 1000;
    normalized = normalized.slice(0, -1);
  } else if (/[0-9][mM]$/.test(normalized)) {
    multiplier = 1000000;
    normalized = normalized.slice(0, -1);
  }
  if (!/^[-+]?[0-9]+(\.[0-9]+)?([eE][-+]?[0-9]+)?$/.test(normalized)) {
    return null;
  }
  const val = Number(normalized) * multiplier;
  if (Number.isNaN(val) || !Number.isFinite(val)) return null;
  return val;
}

/**
 * Computes SHA-256 hex digest for string content in browser or node environments.
 */
async function computeSha256(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  if (typeof crypto !== "undefined" && crypto.subtle) {
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    return Array.from(new Uint8Array(hashBuffer))
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
  }
  // Node.js fallback
  try {
    const { createHash } = await import("node:crypto");
    return createHash("sha256").update(Buffer.from(data)).digest("hex");
  } catch {
    throw new Error("SHA-256 not available in current environment");
  }
}

/**
 * Creates an authoritative SourceDocument representation preserving raw text identity.
 */
export async function createSourceDocument(
  rawText: string,
  id = "src-user-1",
  convention: WordCountConvention = "WORD_COUNT_V1",
): Promise<SourceDocument> {
  const byteLength = new TextEncoder().encode(rawText).length;
  const wordCount = countWords(rawText, convention).count;
  const sha256 = await computeSha256(rawText);

  return {
    id,
    raw_text: rawText,
    sha256,
    byte_length: byteLength,
    word_count: wordCount,
  };
}

export type ParseBudgetResult =
  | {
      status: "SUCCESS";
      budget: RequestedAnswerBudget;
    }
  | {
      status: "NO_BUDGET";
      raw_expression: string;
    }
  | {
      status: "INVALID" | "CONFLICT";
      error: string;
      raw_expression: string;
    };

export function extractAnswerBudget(
  result: ParseBudgetResult | null | undefined,
): RequestedAnswerBudget | null {
  return result && result.status === "SUCCESS" ? result.budget : null;
}

/**
 * Parses downstream deliverable length constraints from expressions like:
 * - "exactly 20,000 words"
 * - "no more than 20,000 words"
 * - "at least 20,000 words"
 * - "between 18,000 and 20,000 words"
 * - "1,000–1,500 words"
 * - "about 20,000 words"
 * - "20,000 tokens"
 * - "20,000 characters"
 * - "10 sentences"
 */
export function parseRequestedAnswerBudget(expr: string): ParseBudgetResult {
  if (!expr || typeof expr !== "string" || !expr.trim()) {
    return { status: "NO_BUDGET", raw_expression: expr ?? "" };
  }

  const raw = expr.trim();
  const normalizedText = normalizeUnicodeDigits(raw).toLowerCase();

  // Unit detection
  let unit: BudgetUnit = "words";
  if (/\b(tokens?|toks?)\b/i.test(normalizedText)) {
    unit = "tokens";
  } else if (/\b(characters?|chars?)\b/i.test(normalizedText)) {
    unit = "characters";
  } else if (/\b(sentences?)\b/i.test(normalizedText)) {
    unit = "sentences";
  } else if (/\b(words?)\b/i.test(normalizedText)) {
    unit = "words";
  } else {
    // If no explicit unit is mentioned, check if purely numeric or contains length hint
    if (!/\b(\d+)\b/.test(normalizedText)) {
      return { status: "NO_BUDGET", raw_expression: expr };
    }
    // Check if there are other word tokens attached that are unrecognized units (e.g. "20000 florbos")
    const words = normalizedText
      .replace(/[^a-z0-9_\s]/g, " ")
      .split(/\s+/)
      .filter((w) => w && !/^\d+$/.test(w));
    const ALLOWED_MODIFIERS = new Set([
      "exact",
      "exactly",
      "precisely",
      "strictly",
      "no",
      "more",
      "than",
      "at",
      "most",
      "under",
      "max",
      "maximum",
      "up",
      "to",
      "least",
      "minimum",
      "min",
      "less",
      "about",
      "approx",
      "approximately",
      "around",
      "between",
      "and",
      "return",
      "length",
      "count",
      "target",
      "output",
      "response",
      "deliverable",
      "final",
      "total",
      "answer",
      "draft",
      "write",
      "generate",
      "produce",
      "of",
      "in",
      "the",
      "is",
      "be",
      "should",
      "must",
      "have",
      "contain",
    ]);
    const unknownWord = words.find((w) => !ALLOWED_MODIFIERS.has(w));
    if (unknownWord) {
      return {
        status: "INVALID",
        error: `Unknown or malformed length unit: "${unknownWord}" in "${expr}"`,
        raw_expression: expr,
      };
    }
    // Default to words
    unit = "words";
  }

  // Range detection: "between X and Y", "X-Y", "X–Y", "X to Y"
  const rangePattern =
    /(?:between\s+)?([0-9][0-9,_eE.]*)\s*(?:-|–|—|to|\band\b)\s*([0-9][0-9,_eE.]*)\s*(?:words?|tokens?|characters?|chars?|sentences?)?/i;
  const rangeMatch = normalizedText.match(rangePattern);
  if (
    rangeMatch &&
    (normalizedText.includes("between") ||
      normalizedText.includes("-") ||
      normalizedText.includes("–") ||
      normalizedText.includes("to") ||
      normalizedText.includes("and"))
  ) {
    const minVal = parseFlexibleNumber(rangeMatch[1]);
    const maxVal = parseFlexibleNumber(rangeMatch[2]);
    if (minVal === null || maxVal === null) {
      return {
        status: "INVALID",
        error: `Malformed numeric range in length expression: "${expr}"`,
        raw_expression: expr,
      };
    }
    if (minVal < 0 || maxVal < 0) {
      return {
        status: "INVALID",
        error: `Negative values forbidden in length budget: ${minVal}, ${maxVal}`,
        raw_expression: expr,
      };
    }
    if (minVal > maxVal) {
      return {
        status: "CONFLICT",
        error: `CONFLICT: Inverted length range [${minVal}, ${maxVal}]`,
        raw_expression: expr,
      };
    }
    const roundedMin = Math.round(minVal);
    const roundedMax = Math.round(maxVal);
    return {
      status: "SUCCESS",
      budget: {
        unit,
        mode: "range",
        target: roundedMax,
        min: roundedMin,
        max: roundedMax,
        raw_expression: expr,
        counting_contract: WORD_COUNT_VERSION,
      },
    };
  }

  // Extract primary number
  const numMatches = normalizedText.match(/[-+]?[0-9][0-9,_eE.]*[kKmM]?/g);
  if (!numMatches || numMatches.length === 0) {
    return { status: "NO_BUDGET", raw_expression: expr };
  }

  const primaryNum = parseFlexibleNumber(numMatches[0]);
  if (primaryNum === null) {
    return {
      status: "INVALID",
      error: `Could not parse valid number in length constraint: "${expr}"`,
      raw_expression: expr,
    };
  }

  if (primaryNum < 0) {
    return {
      status: "INVALID",
      error: `Negative output length is invalid: ${primaryNum}`,
      raw_expression: expr,
    };
  }

  if (primaryNum > Number.MAX_SAFE_INTEGER) {
    return {
      status: "INVALID",
      error: `Output length exceeds safe integer limits: ${primaryNum}`,
      raw_expression: expr,
    };
  }

  const roundedTarget = Math.round(primaryNum);

  // Mode detection
  if (
    /\b(exactly|exact|precisely|strictly)\b/i.test(normalizedText) ||
    normalizedText.startsWith("=")
  ) {
    return {
      status: "SUCCESS",
      budget: {
        unit,
        mode: "exact",
        target: roundedTarget,
        min: roundedTarget,
        max: roundedTarget,
        raw_expression: expr,
        counting_contract: WORD_COUNT_VERSION,
      },
    };
  }

  if (
    /(?:\b(?:no more than|at most|under|max|maximum|up to)\b|<=|<)/i.test(
      normalizedText,
    )
  ) {
    return {
      status: "SUCCESS",
      budget: {
        unit,
        mode: "maximum",
        target: roundedTarget,
        max: roundedTarget,
        raw_expression: expr,
        counting_contract: WORD_COUNT_VERSION,
      },
    };
  }

  if (
    /(?:\b(?:at least|minimum|min|no less than)\b|>=|>)/i.test(normalizedText)
  ) {
    return {
      status: "SUCCESS",
      budget: {
        unit,
        mode: "minimum",
        target: roundedTarget,
        min: roundedTarget,
        raw_expression: expr,
        counting_contract: WORD_COUNT_VERSION,
      },
    };
  }

  if (
    /(?:\b(?:about|approx|approximately|around)\b|~)/i.test(normalizedText)
  ) {
    return {
      status: "SUCCESS",
      budget: {
        unit,
        mode: "approximate",
        target: roundedTarget,
        raw_expression: expr,
        counting_contract: WORD_COUNT_VERSION,
      },
    };
  }

  // Default: exact target
  return {
    status: "SUCCESS",
    budget: {
      unit,
      mode: "exact",
      target: roundedTarget,
      min: roundedTarget,
      max: roundedTarget,
      raw_expression: expr,
      counting_contract: WORD_COUNT_VERSION,
    },
  };
}

function getBudgetLowerBound(b: RequestedAnswerBudget): number | undefined {
  if (b.mode === "exact") return b.target;
  if (b.mode === "minimum") return b.min ?? b.target;
  if (b.mode === "range") return b.min ?? b.target;
  return undefined;
}

function getBudgetUpperBound(b: RequestedAnswerBudget): number | undefined {
  if (b.mode === "exact") return b.target;
  if (b.mode === "maximum") return b.max ?? b.target;
  if (b.mode === "range") return b.max ?? b.target;
  return undefined;
}

/**
 * Checks for conflicts among multiple length constraint statements.
 * For example:
 * "exactly 20,000 words" AND "under 10,000 words" -> CONFLICT
 */
export function detectBudgetConflicts(
  statements: string[],
): { hasConflict: boolean; message?: string; budgets: RequestedAnswerBudget[] } {
  const budgets: RequestedAnswerBudget[] = [];

  for (const stmt of statements) {
    const res = parseRequestedAnswerBudget(stmt);
    if (res.status === "CONFLICT") {
      return { hasConflict: true, message: res.error, budgets: [] };
    }
    if (res.status === "SUCCESS") {
      budgets.push(res.budget);
    }
  }

  if (budgets.length <= 1) {
    return { hasConflict: false, budgets };
  }

  // Cross-compare budgets of the same unit
  for (let i = 0; i < budgets.length; i++) {
    for (let j = i + 1; j < budgets.length; j++) {
      const b1 = budgets[i];
      const b2 = budgets[j];
      if (b1.unit !== b2.unit) continue;

      // Exact vs Exact mismatch
      if (b1.mode === "exact" && b2.mode === "exact" && b1.target !== b2.target) {
        return {
          hasConflict: true,
          message: `[CONFLICT] Conflicting exact length constraints: ${b1.target} vs ${b2.target} ${b1.unit}`,
          budgets,
        };
      }

      const low1 = getBudgetLowerBound(b1);
      const high1 = getBudgetUpperBound(b1);
      const low2 = getBudgetLowerBound(b2);
      const high2 = getBudgetUpperBound(b2);

      // Check if b1's lower bound exceeds b2's upper bound
      if (low1 !== undefined && high2 !== undefined && low1 > high2) {
        if (b1.mode === "exact" && b2.mode === "maximum") {
          return {
            hasConflict: true,
            message: `[CONFLICT] Exact requirement of ${b1.target} ${b1.unit} exceeds maximum of ${high2} ${b2.unit}`,
            budgets,
          };
        }
        if (b2.mode === "exact" && b1.mode === "minimum") {
          return {
            hasConflict: true,
            message: `[CONFLICT] Exact requirement of ${b2.target} ${b2.unit} is below minimum of ${low1} ${b1.unit}`,
            budgets,
          };
        }
        if (b1.mode === "exact" && b2.mode === "range") {
          return {
            hasConflict: true,
            message: `[CONFLICT] Exact requirement of ${b1.target} ${b1.unit} falls outside range [${b2.min ?? b2.target}, ${b2.max ?? b2.target}] ${b2.unit}`,
            budgets,
          };
        }
        if (b1.mode === "range" && b2.mode === "exact") {
          return {
            hasConflict: true,
            message: `[CONFLICT] Exact requirement of ${b2.target} ${b2.unit} falls outside range [${b1.min ?? b1.target}, ${b1.max ?? b1.target}] ${b1.unit}`,
            budgets,
          };
        }
        if (b1.mode === "range" && b2.mode === "range") {
          return {
            hasConflict: true,
            message: `[CONFLICT] Disjoint length ranges [${b1.min ?? b1.target}, ${b1.max ?? b1.target}] and [${b2.min ?? b2.target}, ${b2.max ?? b2.target}] ${b1.unit}`,
            budgets,
          };
        }
        return {
          hasConflict: true,
          message: `[CONFLICT] Minimum constraint (${low1}) exceeds maximum constraint (${high2}) ${b1.unit}`,
          budgets,
        };
      }

      // Check if b2's lower bound exceeds b1's upper bound
      if (low2 !== undefined && high1 !== undefined && low2 > high1) {
        if (b2.mode === "exact" && b1.mode === "maximum") {
          return {
            hasConflict: true,
            message: `[CONFLICT] Exact requirement of ${b2.target} ${b2.unit} exceeds maximum of ${high1} ${b1.unit}`,
            budgets,
          };
        }
        if (b1.mode === "exact" && b2.mode === "minimum") {
          return {
            hasConflict: true,
            message: `[CONFLICT] Exact requirement of ${b1.target} ${b1.unit} is below minimum of ${low2} ${b2.unit}`,
            budgets,
          };
        }
        if (b2.mode === "exact" && b1.mode === "range") {
          return {
            hasConflict: true,
            message: `[CONFLICT] Exact requirement of ${b2.target} ${b2.unit} falls outside range [${b1.min ?? b1.target}, ${b1.max ?? b1.target}] ${b1.unit}`,
            budgets,
          };
        }
        if (b2.mode === "range" && b1.mode === "exact") {
          return {
            hasConflict: true,
            message: `[CONFLICT] Exact requirement of ${b1.target} ${b1.unit} falls outside range [${b2.min ?? b2.target}, ${b2.max ?? b2.target}] ${b2.unit}`,
            budgets,
          };
        }
        if (b1.mode === "range" && b2.mode === "range") {
          return {
            hasConflict: true,
            message: `[CONFLICT] Disjoint length ranges [${b1.min ?? b1.target}, ${b1.max ?? b1.target}] and [${b2.min ?? b2.target}, ${b2.max ?? b2.target}] ${b1.unit}`,
            budgets,
          };
        }
        return {
          hasConflict: true,
          message: `[CONFLICT] Minimum constraint (${low2}) exceeds maximum constraint (${high1}) ${b1.unit}`,
          budgets,
        };
      }
    }
  }

  return { hasConflict: false, budgets };
}

/**
 * Formats a compiled answer-length requirement string according to Section 6.
 * Example:
 * "FINAL OUTPUT LENGTH: Exactly 20,000 words under the specified counting convention."
 */
export function formatCompiledLengthRequirement(budget: RequestedAnswerBudget): string {
  const unitLabel = budget.unit;
  const numStr = budget.target.toLocaleString("en-US");

  switch (budget.mode) {
    case "exact":
      return `FINAL OUTPUT LENGTH: Exactly ${numStr} ${unitLabel} under the specified counting convention.`;
    case "maximum":
      return `FINAL OUTPUT LENGTH: At most ${numStr} ${unitLabel} under the specified counting convention.`;
    case "minimum":
      return `FINAL OUTPUT LENGTH: At least ${numStr} ${unitLabel} under the specified counting convention.`;
    case "range":
      return `FINAL OUTPUT LENGTH: Between ${(budget.min ?? budget.target).toLocaleString("en-US")} and ${(budget.max ?? budget.target).toLocaleString("en-US")} ${unitLabel} under the specified counting convention.`;
    case "approximate":
      return `FINAL OUTPUT LENGTH: Approximately ${numStr} ${unitLabel} under the specified counting convention.`;
    default:
      return `FINAL OUTPUT LENGTH: ${numStr} ${unitLabel} under the specified counting convention.`;
  }
}

export type SourceDuplicationStage =
  | "raw_request"
  | "envelope"
  | "ir"
  | "facts"
  | "protected_fields"
  | "compiler"
  | "renderer"
  | "worker_wasm"
  | "export";

export type SourceDuplicationEntry = {
  stage: SourceDuplicationStage;
  holds_full_text: boolean;
  reference_type: "inline_body" | "source_id_ref" | "sha256_ref" | "not_retained";
  stored_bytes: number;
};

export type SourceDuplicationMap = {
  source_id: string;
  sha256: string;
  byte_length: number;
  word_count: number;
  stages: SourceDuplicationEntry[];
  total_full_copies: number;
  is_amplification_free: boolean;
};

/**
 * Builds SOURCE_DUPLICATION_MAP tracing physical copies across lifecycle stages.
 * For a large source (>= 20,000 words), accidental duplicate full copies is marked a violation.
 */
export function buildSourceDuplicationMap(
  doc: SourceDocument,
  stagesConfig: Record<SourceDuplicationStage, "inline_body" | "source_id_ref" | "sha256_ref" | "not_retained">,
): SourceDuplicationMap {
  const stageNames: SourceDuplicationStage[] = [
    "raw_request",
    "envelope",
    "ir",
    "facts",
    "protected_fields",
    "compiler",
    "renderer",
    "worker_wasm",
    "export",
  ];

  const stages: SourceDuplicationEntry[] = stageNames.map((stage) => {
    const refType = stagesConfig[stage] || "not_retained";
    const holdsFull = refType === "inline_body";
    const storedBytes = holdsFull ? doc.byte_length : refType === "not_retained" ? 0 : 64;
    return {
      stage,
      holds_full_text: holdsFull,
      reference_type: refType,
      stored_bytes: storedBytes,
    };
  });

  const fullCopies = stages.filter((s) => s.holds_full_text).length;
  // Raw request holds the original source; across subsequent stages, duplicate full copies must be 0 for large documents.
  const downstreamCopies = stages.filter((s) => s.stage !== "raw_request" && s.holds_full_text).length;
  const isAmplificationFree = doc.word_count < 20000 || downstreamCopies <= 1;

  return {
    source_id: doc.id,
    sha256: doc.sha256,
    byte_length: doc.byte_length,
    word_count: doc.word_count,
    stages,
    total_full_copies: fullCopies,
    is_amplification_free: isAmplificationFree,
  };
}

