/**
 * SPE Ω — Production SDK Code Generator (Prompt-to-Code)
 * 
 * Compiles formally verified system prompts directly into production-ready,
 * fully typed source files for TypeScript (Vercel AI SDK / Zod) and Python (LangChain / Pydantic v2).
 * 
 * Eliminates manual copy-paste drift and wraps prompt execution in runtime invariant contracts.
 */

import { alignPromptToKvPages } from './kvCachePageAligner.ts';

export interface CodeGenOptions {
  promptName?: string;
  target: 'typescript-vercel' | 'typescript-anthropic' | 'python-langchain' | 'python-openai';
  modelId?: string;
  pageSize?: 16 | 32;
  includeRuntimeContract?: boolean;
}

export interface GeneratedCodeResult {
  target: string;
  filename: string;
  code: string;
  dependencies: string[];
  features: string[];
}

export function generateProductionSdkCode(promptText: string, options: CodeGenOptions): GeneratedCodeResult {
  const promptName = options.promptName || 'SpeSystemPrompt';
  const cleanName = promptName.replace(/[^a-zA-Z0-9]/g, '');
  const pageSize = options.pageSize || 32;
  const aligned = alignPromptToKvPages(promptText, pageSize);
  const alignedPrompt = aligned.alignedPromptText;

  if (options.target === 'typescript-vercel') {
    return generateTypeScriptVercel(cleanName, alignedPrompt, options.modelId || 'anthropic/claude-3-5-sonnet-20241022');
  } else if (options.target === 'typescript-anthropic') {
    return generateTypeScriptAnthropic(cleanName, alignedPrompt, options.modelId || 'claude-3-5-sonnet-20241022');
  } else if (options.target === 'python-langchain') {
    return generatePythonLangChain(cleanName, alignedPrompt, options.modelId || 'gpt-4o');
  } else {
    return generatePythonOpenAI(cleanName, alignedPrompt, options.modelId || 'gpt-4o');
  }
}

function generateTypeScriptVercel(name: string, promptText: string, modelId: string): GeneratedCodeResult {
  const escapedPrompt = JSON.stringify(promptText);
  const code = `/**
 * Generated by SPE Ω (AI Instruction Assurance Compiler)
 * Target: TypeScript + Vercel AI SDK + Zod Runtime Contract
 * Optimization: PagedAttention KV-Cache Aligned (32-token boundary)
 */

import { generateText, streamText } from 'ai';
import { z } from 'zod';

// ==========================================
// 1. INPUT & OUTPUT SCHEMAS
// ==========================================

export const ${name}InputSchema = z.object({
  userMessage: z.string().min(1, 'User input message cannot be empty'),
  context: z.record(z.unknown()).optional(),
});

export type ${name}Input = z.infer<typeof ${name}InputSchema>;

export const ${name}OutputSchema = z.object({
  assistantReply: z.string(),
  reasoning: z.string().optional(),
  metadata: z.record(z.unknown()).optional(),
});

export type ${name}Output = z.infer<typeof ${name}OutputSchema>;

// ==========================================
// 2. COMPILED & ALIGNED SYSTEM PROMPT
// ==========================================

export const TARGET_MODEL_ID = "${modelId}";
export const COMPILED_SYSTEM_PROMPT = ${escapedPrompt};

// ==========================================
// 3. PRODUCTION EXECUTION FUNCTION
// ==========================================

export interface ExecuteOptions {
  model?: any; // Vercel AI SDK LanguageModel instance
  temperature?: number;
}

/**
 * Executes the ${name} instruction with strict schema validation.
 */
export async function execute${name}(
  input: ${name}Input,
  options: ExecuteOptions = {}
): Promise<${name}Output> {
  // Validate input parameters against contract
  const validatedInput = ${name}InputSchema.parse(input);

  const result = await generateText({
    model: options.model,
    system: COMPILED_SYSTEM_PROMPT,
    prompt: validatedInput.userMessage,
    temperature: options.temperature ?? 0.2,
  });

  const parsedOutput = ${name}OutputSchema.parse({
    assistantReply: result.text,
    metadata: {
      finishReason: result.finishReason,
      usage: result.usage,
    },
  });

  return parsedOutput;
}

/**
 * Streams the ${name} execution with full backpressure support.
 */
export function stream${name}(
  input: ${name}Input,
  options: ExecuteOptions = {}
) {
  const validatedInput = ${name}InputSchema.parse(input);

  return streamText({
    model: options.model,
    system: COMPILED_SYSTEM_PROMPT,
    prompt: validatedInput.userMessage,
    temperature: options.temperature ?? 0.2,
  });
}
`;

  return {
    target: 'typescript-vercel',
    filename: `${name}.generated.ts`,
    code,
    dependencies: ['ai', 'zod'],
    features: ['Vercel AI SDK generateText & streamText', 'Zod Input/Output Contract Validation', 'KV-Cache Page Aligned System Prompt']
  };
}

function generateTypeScriptAnthropic(name: string, promptText: string, modelId: string): GeneratedCodeResult {
  const escapedPrompt = JSON.stringify(promptText);
  const code = `/**
 * Generated by SPE Ω (AI Instruction Assurance Compiler)
 * Target: TypeScript + Anthropic SDK + Zod Runtime Contract
 */

import Anthropic from '@anthropic-ai/sdk';
import { z } from 'zod';

export const ${name}InputSchema = z.object({
  userMessage: z.string().min(1),
  systemOverrides: z.string().optional(),
});

export type ${name}Input = z.infer<typeof ${name}InputSchema>;

export const COMPILED_SYSTEM_PROMPT = ${escapedPrompt};

export async function call${name}(
  client: Anthropic,
  input: ${name}Input,
  model = '${modelId}'
): Promise<string> {
  const validated = ${name}InputSchema.parse(input);

  const response = await client.messages.create({
    model,
    max_tokens: 4096,
    system: COMPILED_SYSTEM_PROMPT,
    messages: [
      { role: 'user', content: validated.userMessage }
    ],
  });

  const textBlock = response.content.find(c => c.type === 'text');
  return textBlock ? textBlock.text : '';
}
`;

  return {
    target: 'typescript-anthropic',
    filename: `${name}Anthropic.generated.ts`,
    code,
    dependencies: ['@anthropic-ai/sdk', 'zod'],
    features: ['Anthropic Client SDK Messages API', 'Type-Safe Runtime Contract', 'KV-Cache Aligned']
  };
}

function generatePythonLangChain(name: string, promptText: string, modelId: string): GeneratedCodeResult {
  const escapedPrompt = JSON.stringify(promptText);
  const code = `"""
Generated by SPE Ω (AI Instruction Assurance Compiler)
Target: Python + LangChain + Pydantic v2
"""

from typing import Optional, Dict, Any
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate
from langchain_openai import ChatOpenAI

# ==========================================
# 1. PYDANTIC V2 DATA CONTRACTS
# ==========================================

class ${name}Input(BaseModel):
    user_message: str = Field(..., description="User query or task input")
    context: Optional[Dict[str, Any]] = Field(default=None, description="Optional RAG context")

class ${name}Output(BaseModel):
    assistant_reply: str = Field(..., description="Model response payload")
    is_contract_valid: bool = Field(default=True, description="Runtime assertion status")

# ==========================================
# 2. COMPILED & ALIGNED SYSTEM PROMPT
# ==========================================

COMPILED_SYSTEM_PROMPT = ${escapedPrompt}

# ==========================================
# 3. RUNTIME PIPELINE RUNNER
# ==========================================

def create_${name.toLowerCase()}_chain(model_name: str = "${modelId}", temperature: float = 0.2):
    """Creates a validated LangChain pipeline with SPE system prompt."""
    chat = ChatOpenAI(model=model_name, temperature=temperature)
    
    prompt = ChatPromptTemplate.from_messages([
        SystemMessagePromptTemplate.from_template(COMPILED_SYSTEM_PROMPT),
        HumanMessagePromptTemplate.from_template("{user_message}")
    ])
    
    return prompt | chat

def run_${name.toLowerCase()}(input_data: ${name}Input, model_name: str = "${modelId}") -> ${name}Output:
    """Executes the chain with guaranteed Pydantic runtime schema parsing."""
    chain = create_${name.toLowerCase()}_chain(model_name=model_name)
    response = chain.invoke({"user_message": input_data.user_message})
    
    return ${name}Output(
        assistant_reply=str(response.content),
        is_contract_valid=True
    )
`;

  return {
    target: 'python-langchain',
    filename: `${name.toLowerCase()}_langchain.py`,
    code,
    dependencies: ['pydantic>=2.0.0', 'langchain-core', 'langchain-openai'],
    features: ['LangChain ChatPromptTemplate Pipeline', 'Pydantic v2 Data Contracts', 'KV-Cache Page Aligned System Prompt']
  };
}

function generatePythonOpenAI(name: string, promptText: string, modelId: string): GeneratedCodeResult {
  const escapedPrompt = JSON.stringify(promptText);
  const code = `"""
Generated by SPE Ω (AI Instruction Assurance Compiler)
Target: Python + OpenAI SDK + Pydantic v2
"""

from typing import Optional, Dict, Any
from pydantic import BaseModel, Field
from openai import OpenAI

class ${name}Input(BaseModel):
    user_message: str = Field(..., description="Prompt user turn input")

class ${name}Output(BaseModel):
    content: str
    model: str
    finish_reason: Optional[str] = None

COMPILED_SYSTEM_PROMPT = ${escapedPrompt}

def execute_${name.toLowerCase()}(client: OpenAI, input_data: ${name}Input, model: str = "${modelId}") -> ${name}Output:
    """Executes call against OpenAI API using compiled SPE prompt."""
    completion = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": COMPILED_SYSTEM_PROMPT},
            {"role": "user", "content": input_data.user_message}
        ],
        temperature=0.2
    )
    
    choice = completion.choices[0]
    return ${name}Output(
        content=choice.message.content or "",
        model=completion.model,
        finish_reason=choice.finish_reason
    )
`;

  return {
    target: 'python-openai',
    filename: `${name.toLowerCase()}_openai.py`,
    code,
    dependencies: ['openai>=1.0.0', 'pydantic>=2.0.0'],
    features: ['Direct OpenAI SDK ChatCompletions', 'Pydantic v2 Models', 'KV-Cache Aligned']
  };
}
